### ISSUE TITLE
Universal FS module

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1029]
Similar to the [`@effect-ts/node/FileSystem`](https://github.com/Effect-TS/node/tree/master/packages/node/src/FileSystem), @mikearnaldi suggested the idea to introduce a more universal FS module that could also be used else where e.g. in the browser (see [this project](https://github.com/GoogleChromeLabs/browser-fs-access)) or fully virtualised (e.g. for tests).

**Comment by mikearnaldi** [comment]
Got the idea from TypeScript's Host abstraction where basically the compiler just depends on a Host impl that has access to the filesystem so that the compiler can run regardless of the concrete host. We'd need to isolate the set of features we want for the virtual fs.

**Comment by mikearnaldi** [comment]
closing as it is now part of `@effect/platform`
