### ISSUE TITLE
Universal fetch module

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1031]
It's a common use case to do HTTP requests (e.g. via fetch). We should provide a universal (or multiple platform-specific) modules for `fetch`.

Ideally also with Otel support (see [this issue](https://github.com/open-telemetry/opentelemetry-js/issues/1315#issuecomment-1013093858)).

**Comment by OliverJAsh** [comment]
@tim-smart Was this closed because it was completed or because there's no plans to do this?

**Comment by fubhy** [comment]
@OliverJAsh This has been implemented. See here: https://github.com/Effect-TS/effect/blob/main/packages/platform/src/Http/Client.ts
