### ISSUE TITLE
Background logger

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1155]
Since logging can slow down an application quite significantly it would be nice to have a built-in logger implementation that doesn't log immediately but batches the log statements and logs them in a deferred way. 

## Related

https://twitter.com/buildsghost/status/1509604787213389824?s=20&t=7zETRBub3-E6KrDH3vShjg

**Comment by tim-smart** [comment]
Logger.batched? https://effect-ts.github.io/effect/effect/Logger.ts.html#batched

**Comment by IMax153** [comment]
Closing this issue now that we have a batched logger as Tim mentioned.
