### ISSUE TITLE
DX improvements for 2.0 (e.g. tooling)

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1299]
> NOTE: This issue is WIP

## Effect eslint rules

- [ ] Enforce restrictions of `Do(($) => { ... })`
  - [ ] Prevent branching
  - [ ] Make sure `yield` / `$` is called 
         ![CleanShot 2022-10-11 at 12 55 51](https://user-images.githubusercontent.com/1567498/195072422-4ab90752-2f32-4cc7-8bfe-e7fcb99a9417.png)
  - [ ] ... what else?
- [ ] prevent `===` on things implementing `Equal`
- [ ] Help catch duplicate context tag symbols which should be globally unique
  
### Codegen-driven

- [ ] Help with derived -> opaque type boilerplate `@@opaque`

### Refactor workflows

- [x] wrap/unwrap `pipe` - e.g. `myFn` <> `pipe(myFn)`
- [ ] Curry/uncurry definition site - e.g. `const x = 1` <> `const x = () => 1`
- [x] Curry/uncurry call site - e.g `T.tap(_ => T.log(_))` <> `T.tap(T.log)`
- [ ] Refactor from/to `T.succeed` and `T.sync`
- [ ] `.pipe()` <> `pipe()`
- [x] "Update" explicit type signature / see diff

### Improve error messages

- [ ] Environment dependency mismatch error messages should be improved
  ![image](https://user-images.githubusercontent.com/1567498/199772721-74fe92d5-137a-4b3b-a3bb-c936908ce9e5.png) 
![image](https://user-images.githubusercontent.com/1567498/199772778-4cde2a80-1b33-4513-94f4-a0c43adc1ec0.png)

### Fiber-aware debugger

**Comment by mikearnaldi** [comment]
closing as outdated
