### ISSUE TITLE
Design of Ecosystem Package

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#1311]
The amount of complexity underpinning `Effect` requires unloading complexity to different packages, and with recent decisions to different organizations, namely implementation is distributed across:

- `@fp-ts/core`: higher kinded types and general typeclasses
- `@fp-ts/data`: common data structures and data related typeclasses
- `@fp-ts/optics`: data manipulation a-la-monocle
- `@fp-ts/codec`: serialization, deserialization, arbitraries and domain definition
- `@effect/printer`: pretty printing of documents
- `@effect/core`: effect system together with streams and stm
- `@effect/query`: pipelining and batching of queries
- `@effect/cache`: caching

In addition to that there are a number of organization packages that focus on specific integrations such as:

- `@effect/node`: node specific integration
- `@effect/otel`: open telemetry integration
- `@effect/express`: express based http server
- `@effect/fastify`: fastify based http server
- `@effect/react`: react specific integration
- `@effect/html`: dom/html specific integration
- `@effect/language-service`: ts language service plugin

The final user shouldn't be bothered by this complexity though, they will be interested in learning `Effect` not in learning how it's implemented and using such system having to know where all is in may be an adoption killer.

This issue proposes a framework structure to be published under the npm name `effect` that aims at the average user (not the library author) and wishes to provide them with the right set of tools for most of their problems.

While being unreasonable to include everything in that package I think we should put anything that a normal app user will want to look for that isn't tight to a specific ecosystem (like otel or node)

Current idea:

- `effect/Effect`
- `effect/Effect/Scope`
- `effect/Effect/Supervisor`
- `effect/Layer`
- `effect/Option`
- `effect/Context`
- `effect/Result`
- `effect/Cached`
- `effect/Clock`
- `effect/Deferred`
- `effect/Equals`
- `effect/Hash`
- `effect/Exit`
- `effect/Exit/Cause`
- `effect/Sync`
- `effect/Fiber`
- `effect/Fiber/Ref`
- `effect/Fiber/Scope`
- `effect/Fiber/Id`
- `effect/Hub`
- `effect/Queue`
- `effect/Logger`
- `effect/Logger/LogLevel`
- `effect/Logger/LogSpan`
- `effect/Metric`
- `effect/Random`
- `effect/Ref`
- `effect/Ref/Syncronized`
- `effect/Ref/Scoped`
- `effect/Ref/Subscription`
- `effect/Runtime`
- `effect/Runtime/Flags`
- `effect/Query`
- `effect/Query/DataSource`
- `effect/Query/RequestMap`
- `effect/Query/Cache`
- `effect/Query/Described`
- `effect/Query/Request`
- `effect/Stream`
- `effect/Stream/Channel`
- `effect/Stream/Sink`
- `effect/Stream/Pull`
- `effect/Stream/Take`
- `effect/STM`
- `effect/STM/TArray`
- `effect/STM/TDeferred`
- `effect/STM/TExit`
- `effect/STM/THub`
- `effect/STM/TPriorityQueue`
- `effect/STM/TQueue`
- `effect/STM/TRandom`
- `effect/STM/TReentrantLock`
- `effect/STM/TRef`
- `effect/STM/TSemaphore`
- `effect/STM/TSet`
- `effect/Cache`
- `effect/Cache/EntryStats`
- `effect/Cache/CacheStats`
- `effect/Cache/Lookup`
- `effect/Collection/HashMap`
- `effect/Collection/List`
- `effect/Collection/Chunk`
- `effect/Collection/ReadonlyArray`
- `effect/Collection/NonEmptyReadonlyArray`
- `effect/Collection/Queue`
- `effect/Collection/HashMap`
- `effect/Collection/HashSet`
- `effect/Collection/SortedMap`
- `effect/Collection/SortedSet`
- `effect/Collection/Queue`
- `effect/Collection/MutableHashMap`
- `effect/Collection/MutableHashSet`
- `effect/Collection/MutableQueue`
- `effect/Collection/MutableRef`
- `effect/Collection/WeakIterabeMap`
- `effect/Boolean`
- `effect/Number`
- `effect/String`
- `effect/Duration`
- `effect/Function/Endomorphism`
- `effect/Function/Predicate`
- `effect/Function/Refinement`
- `effect/TypeClass/(Sortable | Monad | Functor | etc...)`

**Comment by steida** [comment]
> I think unifying the application related Effect packages under a single export would make usage so much easier for developers. I 100% support this 🚀 .

Exactly. Give me "$" or "_" so I can explore the API I'm supposed to use.
