### ISSUE TITLE
Friction Points

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#1318]
- [x] TS+ related configs
- [x] Folder structure (underscore prefix)
- [x] Overly lazy functions
- [ ] Lack of examples
- [ ] Lack of documentation
- [ ] Lack of starter projects

**Comment by aniravi24** [comment]
I think using a monorepo setup might help you as well as anyone looking to follow and potentially contribute as well! It's really nice to see everything in one place and for versions to be in sync.

For example, [mantine](https://github.com/mantinedev/mantine) and [remix](https://github.com/remix-run/remix)

I also found [Nx](https://nx.dev/) to be incredibly useful for my projects!
