### ISSUE TITLE
Add link to Tracing UI (e.g. Otel) in trace logs 

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1319]
![CleanShot 2022-11-15 at 12 37 31@2x](https://user-images.githubusercontent.com/1567498/201919967-602a5fd1-7214-4444-aae5-5c648f216265.png)

- e.g. via some kind of callback: `getTracingUiUrl = (spanId, traceId) => 'https://jaeger....'`

**Comment by tim-smart** [comment]
Will mark this as superseded by https://github.com/Effect-TS/effect/issues/1363
