### ISSUE TITLE
Include tsconfig files with each node module

### ISSUE THREAD

**Issue by patroza** [Effect-TS/effect#1364]
For sources to be usable in editor, the default for ctrl/cmd click / go to definition, the tsconfigs should be included.
Otherwise it will load e.g internals via .d.ts references, and all the code gets red squiggles and spam errors.

**Comment by mikearnaldi** [comment]
closed via https://github.com/Effect-TS/effect/commit/d71d560942e7fecfc9abc99b4a2cfe47f19c1811
