### ISSUE TITLE
Decorators as in returns

### ISSUE THREAD

**Issue by Lirik-Keltran** [Effect-TS/effect#1371]
They added decorators to typescript, and why not make decorators like returns in python. This will make it easier to incorporate the effect into an existing project

## Examples from returns
[@safe -> Result[T, Exception]](https://returns.readthedocs.io/en/latest/pages/result.html#decorators)
[@maybe -> Maybe[T]](https://returns.readthedocs.io/en/latest/pages/maybe.html#decorators)

**Comment by mikearnaldi** [comment]
Closing because it is impossible.

1) there is no such a thing as a function decorator, they are only for classes and class methods

2) applying a decorator cannot change the return type of the method
