### ISSUE TITLE
[Question] Looking for structures.

### ISSUE THREAD

**Issue by waynevanson** [Effect-TS/effect#1378]
I'm looking for Reader, Writer and State structures but can't find them.

Am I missing something?

**Comment by mikearnaldi** [comment]
They are not part of Effect, the advise is to use Effect directly, for example State<S> can be simulated with:

```ts
interface NumberState {
  readonly _: unique symbol
}
const NumberState = Tag<NumberState, Ref<number>>("@app/NumberState")
```
