### ISSUE TITLE
[Suggestion] Optional `this` context for `Effect.gen`

### ISSUE THREAD

**Issue by tminich** [Effect-TS/effect#1399]
Coming from `fp-ts` I love the async/await-like generator syntax of `Effect.gen`. One thing that I found a bit awkward is that, as generators have to be full functions, there is no clean context capturing syntax and you have to fall back to (what now feels like) ancient practices of something like `const that = this` before using `Effect.gen`.

For myself and my team I have created a small wrapper that allows an optional second parameter that is handed to the function as `this`. I was wondering if this something useful enough to be folded into the default function:
```typescript
export const gen: <Eff extends EffectGen<any, any, any>, AEff, This = never>(f: (this: This, resume: Adapter) => Generator<Eff, AEff, any>, that?: This) => Effect.Effect<[
    Eff
] extends [never] ? never : [Eff] extends [EffectGen<infer R, any, any>] ? R : never, [
    Eff
] extends [never] ? never : [Eff] extends [EffectGen<any, infer E, any>] ? E : never, AEff> = (f, that) => {
    const _f = that !== undefined ? f.bind(that) : f
    return Effect.gen(_f)
}
```

Example usage:
```typescript
const test_this = {
    value: 2,
    double() {
        return this.value * 2
    }
}

const test_effect = BindingEffect.gen(function* (_) {
    return yield* _(Effect.succeed(this.double()))
}, test_this)

expect(Effect.runSync(test_effect)).to.be.equal(4)
```

**Comment by mikearnaldi** [comment]
Addressed in https://github.com/Effect-TS/effect/pull/1434/commits/f7c250b5918a088865492547397d2541b73b71a3
