### ISSUE TITLE
Quickstart instructions are outdated

### ISSUE THREAD

**Issue by marian-c** [Effect-TS/effect#1401]
A recent change made the quickstart instructions on the website insufficient for someone to get started with this project.

https://github.com/Effect-TS/effect/pull/1395/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R59-R65

This issue refers to the node.js side of the instructions, I didn't try the rest

**Comment by WayneEllery** [comment]
When I tried to follow it and used `pipe` I got the following error: `Cannot find module '@effect/schema/Schema' from 'node_modules/@effect/match/index.js'`

**Comment by marian-c** [comment]
As a workaround, if you're on the affected versions, you can manually add the other dependencies:

```
    "@effect/data": "^0.17.1",
    "@effect/io": "^0.38.0",
    "@effect/match": "^0.32.0",
    "@effect/schema": "^0.33.1",
    "@effect/stm": "^0.22.0",
    "@effect/stream": "^0.34.0",
    "effect": "^2.0.0-next.24",
```

You might want to use the latest versions of these packages, depending on when you see this

**Comment by marian-c** [comment]
@tim-smart 
I see newer versions of `effect` defining also "dependencies", but down the line, one is still missing:

`@effect/match 0.32.0` is still missing the `@effect/schema` dep.

The error that I get is: `Error: Cannot find module '@effect/schema/Schema'`

**Comment by tim-smart** [comment]
/match no longer depends on /schema so this should be resolved now :)
