### ISSUE TITLE
[ReadOnlyArray] Array.isEmptyArray does not perform type narrowing

### ISSUE THREAD

**Issue by samuelebonini** [Effect-TS/effect#1414]
Given a variable `arr` of type `T[]`, I'm noticing that

```
import * as Array from "@effect/data/ReadonlyArray"

if(Array.isEmptyArray(arr)) {
    return;
}
arr; // <-- here arr still has type T[]
```

whereas

```
import * as Array from "@effect/data/ReadonlyArray"

if(!Array.isNonEmptyArray(arr)) {
    return;
}
arr; // <-- here arr has type [T, ...T[]]
```

Am I missing something? Shouldn't the first snippet also exhibit the same behavior, i.e. narrow the type down to a non-empty array?

**Comment by TylorS** [comment]
This is a TypeScript issue AFAIK. Refinement types are good at telling what a type *is*, but not good at what it isn't, unless the type you're refinining is union. However, in this example, we're dealing subtypes of Arrays rather than unions.

**Comment by nandin-borjigin** [comment]
You can get the desired type safety at a cost of double negation (which I wouldn't trade for)

```typescript
import { isNonEmptyArray } from '@effect/data/ReadonlyArray'


function foo<T>(arr: T[]) {
    if (!isNonEmptyArray(arr)) {
        return;
    }

    arr; // [T, ...T[]]
}
``

**Comment by tim-smart** [comment]
Unfortunately we can't fix this, as typescript only allows you to narrow based on what the type _is_, not what it _isn't_. Will close for now.
