### ISSUE TITLE
How should aborted Effects behave?

### ISSUE THREAD

**Issue by midzdotdev** [Effect-TS/effect#1424]
I've taken a pretty thorough look through the docs, and I can't seem to find what I'm looking for - please correct me if it's already there somewhere.

As an example (perhaps an unfortunate start to my first use of Effect), I'm trying to wrap `Upload` from `@aws-sdk/lib-storage` as an Effect with relatively sound types.

The function accepts in an `AbortController` (a different type that is incompatible with Node's own one), and when it's aborted it throws an error. I was planning to wrap this thing in `Effect.tryPromise` anyway, which led me to wonder whether effects should succeed or fail when aborted.

In this case, `A` is `void`, so I can just `return Effect.succeed(undefined)`, but:
1. **I don't know if this is correct**
2. what if I couldn't satisfy the return type after aborting/interrupting?

```ts
export interface MemoryFile {
  path: string;
  contentType: string;
  getBody: () => Promise<Readable>;
}

export const streamFileToS3 = (file: MemoryFile) =>
  Effect.tryPromise<unknown, void>({
    try: async (signal) =>
      await new Upload({
        client: s3Client,
        params: {
          Bucket: My_BUCKET,
          Key: file.path,
          ContentType: file.contentType,
          ACL: "public-read",
          Body: await file.getBody(),
        },
        abortController: awsAbortController(signal),
      }).done(),
    catch: (e) => {
      if (e instanceof Error) {
        if (e.name === "AbortError") {
          return Effect.succeed(undefined);
        }
      }

      return Effect.fail(e);
    },
  });

export const awsAbortController = (signal: AbortSignal): any => ({
  signal,
  abort: () => {},
});
```

`@aws-sdk/lib-storage` just exposes some helpers by wrapping `@aws-sdk/s3-client` functionality. I'm wondering whether to do away with it and make my own multi-part upload because the underlying package has more specific error classes rather than just `Error`. _If you could provide some guidance given this context, that would be very helpful too._

Thanks :)

**Comment by datner** [comment]
Hey! This would be better addressed in our discord, you're welcome to join

interruptions are handled within effect, meaning I don't believe you will need to handle the error raised by the interruption explicitly. 
```ts
export interface MemoryFile {
  path: string;
  contentType: string;
  getBody: () => Promise<Readable>;
}

export class UploadError extends Data.taggedClass("UploadError")<{ reason: unknown }>{}

export const streamFileToS3 = (file: MemoryFile) =>
  // You don't have to explicitly type the operator, most of effect has very strong inference you can rely on
  Effect.tryPromise({
    // the signature here is <A>(signal: AbortSignal) => Promise<A>
    // so you can skip the async await
    try: (signal) =>
      new Upload({
        client: s3Client,
        params: {
          Bucket: My_BUCKET,
          Key: file.path,
          ContentType: file.contentType,
          ACL: "public-read",
          Body: await file.getBody(),
        },
        abortController: awsAbortController(signal),
      }).done(),
    // the `catch` here is mostly used for mapping the error from the operation so it's no longer `unknown`.
    // It's perfectly reasonable to just create a wrapper, I can explain in more detail in the discord if you want
    catch: (reason) => new UploadError({ reason })
  });

export const awsAbortController = (signal: AbortSignal): any => ({
  signal,
  abort: () => {},
});
```

**Comment by mikearnaldi** [comment]
Closing because the question was answered and further discussions are better addressed in Discord
