### ISSUE TITLE
`npm init effect`

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1438]
We should build a `create-effect` package to enable the `npm init effect` flow.

See https://docs.npmjs.com/cli/v10/commands/npm-init

**Comment by schickling** [comment]
Oh looks like the [`create-effect` package on NPM](https://www.npmjs.com/package/create-effect) is already taken by @s-yadav. I'll try to get in touch to see whether we can get the package since it seems to be unused. :)

**Comment by tim-smart** [comment]
@schickling did you manage to snag the package name?

**Comment by mikearnaldi** [comment]
superseded by `npm create effect-app`
