### ISSUE TITLE
Target invocation illegal exception

### ISSUE THREAD

**Issue by mattiamanzati** [Effect-TS/effect#1458]
In some environments like react native with metro trying to use any delay will result in this exception.

It is raised because the timeout module aliases setTimeout into timeoutModule.set

That means that calling timeoutModule.set will put "this" as timeoutModule instead of the global window and will raise the exception said before.

As a fix a function should be introduced or (harder) bind setTimeout this to the window object in dom and global into react native.

Fix example:

![image](https://github.com/Effect-TS/effect/assets/13787614/caa1f3e8-f6de-4337-8fa9-86a0e638d259)

**Comment by fubhy** [comment]
I'd rather want this to not be necessary at all but without it the scheduler doesn't work in Bun at all. I was initially hopeful that this was just going to be a temporary hotfix but the recent comments in the Bun repo suggest that it might stay like this: https://github.com/oven-sh/bun/issues/3333

I wonder if we should attempt to fix this as you suggested or remove the hotfix altogether and accept that it won't work in Bun for the time being.

**Comment by fubhy** [comment]
... I guess the same also might apply to `clear`?
