### ISSUE TITLE
Support embedding Effect without "leaking"

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1478]
- Also consider Otel

**Comment by TylorS** [comment]
It's kinda hard to tell from just the title and description what it is this issue should cover. Are you asking for the ability to create Effect-based super-types like Stream does for Effect?

**Comment by mikearnaldi** [comment]
> It's kinda hard to tell from just the title and description what it is this issue should cover. Are you asking for the ability to create Effect-based super-types like Stream does for Effect?

that's to better support bundling effect into third party libraries like contentlayer

**Comment by mikearnaldi** [comment]
Addressed in https://github.com/Effect-TS/effect/pull/1564

**Comment by schickling** [comment]
Example project by @tim-smart 🙏 
https://github.com/tim-smart/openai-client-demo
