### ISSUE TITLE
Consider adding support for cron expressions for Schedule

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/effect#1524]
### What is the problem this feature would solve?

There is currently no good way to translate cron expressions into an instance of Schedule. Although a "cron-like" api exists (i.e. `dayOfWeek`, `dayOfMonth`, etc.) it isn't very convenient. 

### What is the feature you are proposing to solve the problem?

A cron string would be more convenient and familiar vs writing using the current set of `dayOfMonth`, `dayOfWeek`, etc. api. 
```ts
Schedule.cron("28 2 7 * *")
```

**Comment by EmanueleGurini** [comment]
can i grab it?

**Comment by fubhy** [comment]
> can i grab it?

Sure!

**Comment by justinhj** [comment]
Just a thought, I wonder if it would be useful to write a tagged template that turns strings into Schedules. 
You could write:
``` 
const schedule = cron`28 2 7 * *`
```

**Comment by fubhy** [comment]
> can i grab it?

Hey @EmanueleGurini, are you still working on this?

**Comment by EmanueleGurini** [comment]
Hey @fubhy, yes, I'm still working on it. I'm a bit slow because I'm discovering Effect

**Comment by fubhy** [comment]
> Hey @fubhy, yes, I'm still working on it. I'm a bit slow because I'm discovering Effect

That's fine. No worries! Just wanted to check in. I see you are already in our Discord community. Let us know if you have any questions.

**Comment by mikearnaldi** [comment]
> Just a thought, I wonder if it would be useful to write a tagged template that turns strings into Schedules. You could write:
> 
> ```
> const schedule = cron`28 2 7 * *`
> ```

what would be the advantage over `cron("28 2 7 * *")` ?

**Comment by justinhj** [comment]
> what would be the advantage over cron("28 2 7 * *") ?

yeah not much 🥲
