### ISSUE TITLE
CJS-ESM Hazard

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#1561]
This issue to document & keep track of the decisions around modules the lib should export, the options that we have available are:

1) CJS only, doesn't allow for tree-shaking & doesn't allow smooth usage when using ESM (albeit ESM being able to import CJS). Otherwise works great.
2) Dual ESM / CJS, allows for usage in both CJS and ESM environment but exposes the user to risks of state duplication when both copies are imported.
3) Dual ESM / CJS with ESM-Proxy, this is like 2 but in addition exposes a set of ESM modules that proxy to CJS so that when resolved by node regardless of which style we use we end up with a single state (generated from CJS). This looks good at first sight but it doesn't work with a lib that is exposed as "2" (e.g. fast-check is impossible to use from schema). Also it trips build tooling such as vitest who have non standard module resolution (albeit this can be considered a BUG of such tools)
4) ESM-only, it would be all good but unfortunately it is problematic to force consumers into ESM as the ecosystem doesn't yet homogeneously support ESM (and with all probability never will).

I believe our only valid choice is "2.5" in the sense that 3 is impractical as it forbids third party dependencies that we have no control over and 2 alone is a call for bugs. 2.5 is what we've been doing by using `globalValue("id", maker)` to isolate the pieces of state that should be shared globally. It is a bit error prone as there is no check to know when we are allocating state and it's easy to forget

**Comment by fubhy** [comment]
I'm generally a fan of pure ESM. We discussed this at length in Discord already. TL;DR: I strongly believe that ESM is the "right" path forward for the ecosystem. Explciitly guiding new users on that path by only exposing ESM is a boon imho.

I don't think there's a problem with fresh users of `effect` in a green field scenario. New users would be running on our documentation, tutorials and template guardrails (e.g. `pnpnx create-effect`)

Hence, I think the only user group who would truly suffer if we only ship pure ESM would be veterans working on large deeply interwoven code bases. The kind of user that likely knows what's happening but has no way to make it work because they can't get rid of their year long tail of legacy CJS dependencies in their projects.

Realistically though, newcomers are not a concern in my opinion.

All that considered, In retrospect, I think going back to [2] but explicitly and forcefully failing hard in case a dual package import is detected at runtime is the least cumbersome would possibly lead the best outcome for all parties while only locking out a small portion of potential uses (those who would otherwise run into an obscure dual package hazard at runtime)

**Comment by fubhy** [comment]
Maybe I'm missing sth. but why do we need to do that at all? Why not just drop a root scope side effect into our core most module(s)?

**Comment by tim-smart** [comment]
Currently you can have two different versions of effect and still have a working app, because of the global value workaround.

**Comment by fubhy** [comment]
Yeah but my point is we could just not allow that to keep things simple and predictable. The worst outcome is subtle runtime bugs that go undiscovered and eventually come to haunt you. Failing early and failing hard might be a viable alternative here.

**Comment by IMax153** [comment]
I'm personally interested in seeing if the 2.5 approach of supporting ESM/CJS (without an ESM proxy) using the `globalValue` helper will work for us long term. We can also work on an ESLint rule to try to help us out with this (it can be dumb at first, like detecting when we are creating a `FiberRef` with the FiberRef constructors.

I also think there is no harm in logging a warning to users if `effect` is imported twice somehow, similar to what React does if you import two versions of the library. I think this benefits users not just for the dual package hazard issues, but also for those who simply end up with two versions of `effect` somehow.

**Comment by fubhy** [comment]
> I'm personally interested in seeing if the 2.5 approach of supporting ESM/CJS (without an ESM proxy) using the `globalValue` helper will work for us long term. We can also work on an ESLint rule to try to help us out with this (it can be dumb at first, like detecting when we are creating a `FiberRef` with the FiberRef constructors.
> 
> I also think there is no harm in logging a warning to users if `effect` is imported twice somehow, similar to what React does if you import two versions of the library. I think this benefits users not just for the dual package hazard issues, but also for those who simply end up with two versions of `effect` somehow.

I could live with this compromise. Log a warning, loud and clear (instead of the hard fail that I suggested) but try to work around runtime issues on a "best effort" basis

**Comment by mikearnaldi** [comment]
Not sure logging is a good idea, the issue isn't limited to effect but to any lib built on top, you could have `@effect/platform` duplicated too

I think we should decide if either we support running with duplicated modules or we don't, I'd opt for supporting the case.

Another scenario is folks bundling effect in their own libs, as much as this is a bad idea, some folks are worried about "effect" as an explicit dependency and would like to bundle it. In such case we will be running multiple versions anytime the user is also running effect

**Comment by fubhy** [comment]
> I think we should decide if either we support running with duplicated modules or we don't, I'd opt for supporting the case.

The problem I have with that is the mine field of potential (especially unforeseen) issues we'd be willingly putting ourselves in. This past year I went back and forth between "I totally get CJS & ESM duality now" and "Damn, another weird issue" numerous times. At this point I cannot claim with certainty that we can prevent all potential runtime issues with the workarounds we've named so far (`globalValue`, avoiding `instanceof`, etc.). I'm sure there are still dragons we've not taken into account yet. There are just too many (unknown) edge cases and too many things to constantly be on our toes about (remembering to apply `globalValue`, etc.) whenever we author or review a PR in the future.

I'm worried that we are going to put ourselves through a lot of (future) pain (maintenance, user support, etc.) if we make the wrong decision here, whatever the wrong decision is (I really don't know).

> Another scenario is folks bundling effect in their own libs, as much as this is a bad idea, some folks are worried about "effect" as an explicit dependency and would like to bundle it. In such case we will be running multiple versions anytime the user is also running effect

That doesn't sound like sth. we should support or encourage though, does it?

**Comment by mikearnaldi** [comment]
> > I think we should decide if either we support running with duplicated modules or we don't, I'd opt for supporting the case.
> 
> The problem I have with that is the mine field of potential (especially unforeseen) issues we'd be willingly putting ourselves in. This past year I went back and forth between "I totally get CJS & ESM duality now" and "Damn, another weird issue" numerous times. At this point I cannot claim with certainty that we can prevent all potential runtime issues with the workarounds we've named so far (`globalValue`, avoiding `instanceof`, etc.). I'm sure there are still dragons we've not taken into account yet. There are just too many (unknown) edge cases and too many things to constantly be on our toes about (remembering to apply `globalValue`, etc.) whenever we author or review a PR in the future.
> 
> I'm worried that we are going to put ourselves through a lot of (future) pain (maintenance, user support, etc.) if we make the wrong decision here, whatever the wrong decision is (I really don't know).
> 
> > Another scenario is folks bundling effect in their own libs, as much as this is a bad idea, some folks are worried about "effect" as an explicit dependency and would like to bundle it. In such case we will be running multiple versions anytime the user is also running effect
> 
> That doesn't sound like sth. we should support or encourage though, does it?

- supporting users with large production systems is 100% a priority of Effect, we can't dismiss folks that have been using node in prod for years, they are our primary addressable market

- I think bundling effect is dumb but I can't prohibit people from doing it, effect has a learning curve and it isn't yet as standard as a react would be so, while being a dumb thing to do, if there is a lib author that wants to leverage effect internally we should support it while advocating for the correct solution (effect in peerDependencies)

**Comment by fubhy** [comment]
> supporting users with large production systems is 100% a priority of Effect, we can't dismiss folks that have been using node in prod for years, they are our primary addressable market

I get that and I also want to suppor them! As mentioned in our previous discussions and on Discord, these are definitely the type of users that I can see in a lot of pain if we drop CJS. To me they are the one exception where I agree that CJS is still necessary.

I am simply worried and uncertain about the "how" (as we all are). I don'tI like the possibility of silent, deferred failures or wonkiness and hard-to-debug runtime scenarios that users might experience at different points during their programs lifetimes. I'd rather have guaranteed, clear messaging and hard failures. Ideally before actually running the application.

**Comment by mikearnaldi** [comment]
https://github.com/Effect-TS/effect/pull/1564

This progresses on the idea, it tracks versions and isolate state between different versions so effectively we can run two independent versions of effect without issues

Ofc client state is also to be considered but realistically the only stateful piece of effect a client uses are tags and when tags have identifiers they become globally shared, note that tags are also using globalValue so they become versioned like any other effect

**Comment by fubhy** [comment]
I just gave `tshy` (https://github.com/isaacs/tshy) a shot.

It is following the ideas of `2.5` as [described by Mike](https://github.com/Effect-TS/effect/issues/1561#issue-1960090987) (CJS & ESM exports and advocating for awareness around duplicate state. I'm starting to feel a bit more convincend about this. Sorry, I've been burned by this too many times so please excuse me trying to tread carefully here ;-).

This is from the `tshy` README:

> ["Dual Module Hazard" is a fact of life anyway](https://github.com/isaacs/tshy#dual-module-hazard-is-a-fact-of-life-anyway)
> Since the advent of npm, circa 2010, module in node have been potentially duplicated in the dependency graph. Node's nested node_modules resolution algorithm, added in Node 0.4, made this even easier to leverage, and more likely to occur.
> 
> So: as a package author, you cannot safely rely on there being exactly one copy of your library loaded at run-time.
> 
> This doesn't mean you shouldn't care about it. It mean that you should take it into consideration always, whether you are using a hybrid build or not.
> 
> If you need to ensure that exactly one copy of something exists at run-time, whether using a hybrid build or not, you need to guard this with a check that is not dependent on the dependency graph, such as a global variable.

That said, `tshy` doesn't work 100% yet but it is *very* close to our pre-`preconstruct` setup. Worth to keep an eye on it if we want to drop some of our custom made tooling & config in the future.

In the meantime, I suggest we revert back to our pre-`preconstruct` setup, with the following adjustments compared to our pre-`preconstruct` configuration (Max and I have already started with that):

- Use named exports (some bundler [e.g. parcel] and ts issues remain with wildcard exports)
- Bump to `NodeNext` and `ES2022`

I would also suggest to move back to absolute imports.

To validate that everything is working correctly in all scenarios, we should consider to:

- Add shallow consumer acceptance test fixtures / test apps (e.g. Node ESM, Node CJS, Bun, Parcel, Vitest, Webpack)
- Add a CI test matrix for `node` (as is now), `jsdom` and `edge` vitest environments

Additionally we should investigate how to best ship `tsconfig.json` with our `dist` or otherwise make .d.ts fully explorable in `dist`  without errors (there are still issues with some custom runtimes like CloudFlare workers).

Does this sound like a reasonable battle plan?

**Comment by mikearnaldi** [comment]
> I just gave `tshy` (https://github.com/isaacs/tshy) a shot.
> 
> It is following the ideas of `2.5` as [described by Mike](https://github.com/Effect-TS/effect/issues/1561#issue-1960090987) (CJS & ESM exports and advocating for awareness around duplicate state. I'm starting to feel a bit more convincend about this. Sorry, I've been burned by this too many times so please excuse me trying to tread carefully here ;-).
> 
> This is from the `tshy` README:
> 
> > ["Dual Module Hazard" is a fact of life anyway](https://github.com/isaacs/tshy#dual-module-hazard-is-a-fact-of-life-anyway)
> > Since the advent of npm, circa 2010, module in node have been potentially duplicated in the dependency graph. Node's nested node_modules resolution algorithm, added in Node 0.4, made this even easier to leverage, and more likely to occur.
> > So: as a package author, you cannot safely rely on there being exactly one copy of your library loaded at run-time.
> > This doesn't mean you shouldn't care about it. It mean that you should take it into consideration always, whether you are using a hybrid build or not.
> > If you need to ensure that exactly one copy of something exists at run-time, whether using a hybrid build or not, you need to guard this with a check that is not dependent on the dependency graph, such as a global variable.
> 
> That said, `tshy` doesn't work 100% yet but it is _very_ close to our pre-`preconstruct` setup. Worth to keep an eye on it if we want to drop some of our custom made tooling & config in the future.
> 
> In the meantime, I suggest we revert back to our pre-`preconstruct` setup, with the following adjustments compared to our pre-`preconstruct` configuration (Max and I have already started with that):
> 
> * Use named exports (some bundler [e.g. parcel] and ts issues remain with wildcard exports)
> * Bump to `NodeNext` and `ES2022`
> 
> I would also suggest to move back to absolute imports.
> 
> To validate that everything is working correctly in all scenarios, we should consider to:
> 
> * Add shallow consumer acceptance test fixtures / test apps (e.g. Node ESM, Node CJS, Bun, Parcel, Vitest, Webpack)
> * Add a CI test matrix for `node` (as is now), `jsdom` and `edge` vitest environments
> 
> Additionally we should investigate how to best ship `tsconfig.json` with our `dist` or otherwise make .d.ts fully explorable in `dist` without errors (there are still issues with some custom runtimes like CloudFlare workers).
> 
> Does this sound like a reasonable battle plan?

Does sound like a good plan yeah
