### ISSUE TITLE
Documentation for _Unions of Case Classes_ wrong / outdated

### ISSUE THREAD

**Issue by Clindbergh** [Effect-TS/effect#1572]
### What is the type of issue?

Documentation sample code not working.

### What is the issue?

The documentation for [Unions of Case Classes](https://www.effect.website/docs/data-types/data#unions-of-case-classes) is wrong or outdated. 

This code no longer seems to work:

```typescript

// Define a union type using TaggedEnum
type HttpError = Data.TaggedEnum<{
  InternalServerError: { reason: string }
  NotFound: {}
}>
 
// Create constructors for specific error types
const { NotFound, InternalServerError } = Data.taggedEnum<HttpError>()
```

instead the sample posted in #1556  seems to work, e.g.:

```typescript

// Create constructors for specific error types
    const HttpError = Data.taggedEnum<HttpError>()
    HttpError('InternalServerError');
    HttpError('NotFound');
```

### Where did you find it?

https://www.effect.website/docs/data-types/data#unions-of-case-classes

**Comment by gcanti** [comment]
@Clindbergh I can repro, it works fine with `effect@latest` (2.0.0-next.52 published 1 day ago)

**Comment by Clindbergh** [comment]
Sorry, I have been on `2.0.0-next.47`. On the `effect@latest` it works. Thanks!

---

Offtopic:

Is it possible to avoid mentioning fixed values?

E.g.

```typescript
type HttpError = Data.TaggedEnum<{
  InternalServerError: { reason: string, severe: 'no', code: '500' }
  NotFound: { severe: 'yes', code: '404'  }
}>


// Create constructors for specific error types
const { NotFound, InternalServerError } = Data.taggedEnum<HttpError>()

// How can mentioning 'severe' be avoided?
const error = NotFound({ severe: 'yes', code: '404' });

```

Or is there another recommended approach?

**Comment by gcanti** [comment]
> Is it possible to avoid mentioning fixed values?

With the current API, no, there is no way for Data.taggedEnum to know at runtime how to handle those literals
