### ISSUE TITLE
Tracing has wrong timestamps when running in RN

### ISSUE THREAD

**Issue by DomiR** [Effect-TS/effect#1591]
https://github.com/Effect-TS/effect/blob/ee60fe277e4636bb354f6cea4bbf4993b7b3d535/src/internal/clock.ts#L50

This code does not look right. In RN performance is available and performance.now() is a monotonic clock value, but performance.timeOrigin is not available. This means origin will Date.now() and the method will effectively return Date.now() + performance.now() which will be some time in the future.

I guess we should just extend the if clause in line 46 and check if performance is avaliable AND "timeOrigin" in performance and fallback to Date.now() earlier as I don't see why we ever would add performance.now() to Date.now().

**Comment by DomiR** [comment]
Thanks for the patch. But why not return Date.now() early? We are now subtracting then adding the same (even worse maybe a bit off) number, namely performance.now().

**Comment by tim-smart** [comment]
Do you mean returning `() => BigInt(Date.now()) * bigint1e6` like a few lines above? That is an IIFE (immediately invoked fn) that returns the actual function that is eventually used.

So it captures the origin once, then re-uses it for the following invocations of the returned function.

**Comment by DomiR** [comment]
I mean this part: https://github.com/Effect-TS/effect/blob/ee60fe277e4636bb354f6cea4bbf4993b7b3d535/src/internal/clock.ts#L46-L48. As I understand it's the fallback for envs that do not have `performance.now()` available.

So I think we could extend the if clause like this:
```
// check if performance and performance.timeOrigin is available, otherwise fallback to Date.now() as nano-seconds
if (typeof performance === "undefined" || !("timeOrigin" in performance) || typeof performance.timeOrigin !== "number") {
    return () => BigInt(Date.now()) * bigint1e6
}

// otherwise add performance.now() to performance.timeOrigin and return as nano-seconds
return (BigInt(Math.round(performance.timeOrigin)) + BigInt(Math.round(performance.now()) * bigint1e6
```

**Comment by tim-smart** [comment]
It is not the same, as the origin call to performance.now() is only run once when the module is initiated, so subsequent runs will be calculating the offset between the origin point in time and the call of the resulting function.

**Comment by tim-smart** [comment]
So the final call is:

```ts
  return () = (cachedDateNowValue - cachedPerformanceNowValue) + BigInt(Math.round(performance.now() * 1_000_000))

**Comment by DomiR** [comment]
Omg, mb 🫠 Thanks for clarifying!
