### ISSUE TITLE
Investigate optimized build setups (e.g. bundling/code-splitting/tree-shaking etc)

### ISSUE THREAD

**Issue by schickling** [Effect-TS/effect#1816]
We should investigate optimized build setups for Effect CLI apps e.g. using bundling techniques that leverage code-splitting and tree-shaking on a per-command basis. e.g. printing the top-level help command shouldn't yet load all the code for the actual commands etc ([see the Oclif docs](https://oclif.io/docs/features#super-speed)).

**Comment by mikearnaldi** [comment]
closing as out of scope of Effect/cli that is purely a library and doesn't target specific build setups. This is already possible using dynamic imports if a user wants such behaviour
