### ISSUE TITLE
S.identifier after S.attachPropertySignature is ignored, makes errors less useful

### ISSUE THREAD

**Issue by alex2** [Effect-TS/effect#1821]
### What version of `@effect/schema` is running?

0.56.0

### What steps can reproduce the bug?

```typescript
const NoAttachedProperty = S.struct({
  $ref: S.string,
}).pipe(S.identifier("NoAttachedProperty"));

const works = S.parseEither(NoAttachedProperty)("foo");

// The expected schema identifier is rendered by `formatErrors`:
// error(s) found
// └─ Expected NoAttachedProperty, actual "foo"
console.log(
  Either.isLeft(works) ? formatErrors(works.left.errors) : ""
);

const AttachedProperty = S.struct({
  $ref: S.string,
}).pipe(S.attachPropertySignature("_tag", "a"), S.identifier("AttachedProperty"));

const noWorks = S.parseEither(AttachedProperty)("foo");

// error(s) found
// └─ Expected <anonymous type literal schema>, actual "foo"
//                  ^ The expected schema identifier is not rendered
console.log(
  Either.isLeft(noWorks) ? formatErrors(noWorks.left.errors) : ""
);
```

### What is the expected behavior?

I would expect formatErrors to render the following tree with the passed identifier:

```
error(s) found
└─ Expected AttachedProperty, actual "foo"
```

### What do you see instead?

```
error(s) found
└─ Expected <anonymous type literal schema>, actual "foo"
```

### Additional information

`AST.to` recurses into the `to` child from the `Transform` parent node ignoring the annotations, resulting in significantly less useful error messages. I've described this issue with regard to a particular situation I ran into but this would apply to any similar situation where annotations are added to a transform node.

**Comment by gcanti** [comment]
https://github.com/Effect-TS/effect/pull/1842
