### ISSUE TITLE
Get combinator to access (nested) properties of a struct

### ISSUE THREAD

**Issue by florianbepunkt** [Effect-TS/effect#1826]
### What is the problem this feature would solve?

```ts
const A = S.struct({
  b: S.string,
  c: S.struct({ d: S.boolean })
});

const B = A.pipe(S.get("b")); // S.Schema<string, string>
const D = A.pipe(S.get("c.d")); // S.Schema<boolean, boolean>

```

### What is the feature you are proposing to solve the problem?

A new combinator that allows to get parts of a schema.

### What alternatives have you considered?

Declaring parts of my schema that I want to reuse explicitly. But often this only adds syntactic noise.

**Comment by gcanti** [comment]
Resolved in `@effect/schema 0.64.x`, a `fields` property has been exposed:

```ts
import * as S from "@effect/schema/Schema"

const A = S.struct({
  b: S.string,
  c: S.struct({ d: S.boolean })
})

const B = A.fields.b // S.$string
const D = A.fields.c.fields.d // S.$boolean
```
