### ISSUE TITLE
Export as named module

### ISSUE THREAD

**Issue by pradyuman** [Effect-TS/effect#1831]
### Current Behavior

Currently, you have to use a [namespace import](https://github.com/effect-ts/schema#getting-started) to use Schema.

### Desired Behavior

If I were to use this in a larger organization, being able to use a named import would make this easier for others to grok (and also easier to use with intellisense):
```
import { S } from "@effect/schema/Schema"
```

Both [Effect](https://www.effect.website/docs/essentials/importing) and zod support this pattern currently.

**Comment by gcanti** [comment]
(using current version 0.64.x)

```ts
import { Schema } from "@effect/schema"
// or
import { Schema as S } from "@effect/schema"
```
