### ISSUE TITLE
Defaulting nested partial struct properties

### ISSUE THREAD

**Issue by codybrouwers** [Effect-TS/effect#1832]
### Current Behavior

The current behaviour of `withDefault` works on a single level of `S.optional` as shown in the docs example:

```javascript
const schema1 = S.struct({
  a: S.optional(S.number).withDefault(() => 0),
});
S.parseEither(schema1)({}); // => { _tag: 'Right', right: { a: 0 } }
```

But when you have a nested optional struct that has a `withDefault`, the default doesn't apply.

```javascript
const schema2 = S.struct({
  a: S.optional(
    S.struct({
      b: S.optional(S.number).withDefault(() => 0),
    }),
  ),
});
S.parseEither(schema2)({}); // => { _tag: 'Right', right: {} }
```

### Expected behavior

I would expect that the below would happen:

```javascript
const schema3 = S.struct({
  a: S.optional(
    S.struct({
      b: S.optional(S.number).withDefault(() => 0),
    }),
  ),
});
S.parseEither(schema3)({}); // => { _tag: 'Right', right: { a: { b: 0 } } }
```

Maybe this is intentional but if so I found it counter intuitive to having a default for a property.

Thanks for your time!

### Your environment

Which versions of `@effect/schema` are affected by this issue? Did this work in previous versions of `@effect/schema`?

| Software      | Version(s) |
| ------------- | ---------- |
| @effect/schema |      0.33.1      |
| TypeScript    |    5.1.6        |

**Comment by gcanti** [comment]
Update: now that we have constructors (`make`) the simplest solution is setting the default using them:

```ts
import { Schema as S } from "@effect/schema"

const Foo = S.Struct({
  a: S.Number.pipe(S.optional({ default: () => 1 })),
  b: S.String.pipe(S.optional({ default: () => "hello" }))
})

const Bar = S.Struct({
  foo: Foo.pipe(S.optional({ default: () => Foo.make({}) }))
})

console.log(S.decodeUnknownEither(Bar)({})) // { _id: 'Either', _tag: 'Right', right: { foo: { a: 1, b: 'hello' } } }
console.log(S.decodeUnknownEither(Bar)({ foo: undefined })) // { _id: 'Either', _tag: 'Right', right: { foo: { a: 1, b: 'hello' } } }
```
