### ISSUE TITLE
Add `optionFromEmptyString`

### ISSUE THREAD

**Issue by FedericoBiccheddu** [Effect-TS/effect#1836]
### Current Behavior

At the moment I did define the following schema to handle empty strings as `Option`.

```ts
const optionFromEmptyString = pipe(
  Schema.string,
  Schema.transform(
    Schema.optionFromSelf(Schema.string),
    (s) => s.length > 0 ? Option.some(s) : Option.none(),
    (s) => Option.getOrElse(s, () => '')
  )
)
```

### Desired Behavior

Having the schema implemented in `@effect/schema`

### Suggested Solution

```ts
const optionFromEmptyString = pipe(
  Schema.string,
  Schema.transform(
    Schema.optionFromSelf(Schema.string),
    (s) => s.length > 0 ? Option.some(s) : Option.none(),
    (s) => Option.getOrElse(s, () => '')
  )
)
```

### Who does this impact? Who is this for?
I think everyone who uses `Schema` with front-end forms or where `null` cannot be used. Eg: forms returns empty strings when are submitted.

### Describe alternatives you've considered

Declare the schema at app level.

### Your environment

| Software      | Version(s) |
| ------------- | ---------- |
| @effect/schema | 0.15.1           |
| TypeScript    | 5.1.6           |

**Comment by gcanti** [comment]
Closing in favour of https://github.com/Effect-TS/effect/issues/3335

@FedericoBiccheddu you may want to join the discussion here https://discordapp.com/channels/795981131316985866/1265704338257481778/1265949127334826048
