### ISSUE TITLE
Add context tracking to Schema

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#1873]
### What is the problem this feature would solve?

Tracking context usage in schema, currently it's only possible to effects that don't access context (or hack it).

### What is the feature you are proposing to solve the problem?

Adding either:
- a single parameter `R` that tracks requirements of both encoding and decoding
- two different parameters `REnc` and `RDec` to track requirements of encoding and decoding independently

Note that for the unsafe parse functions (sync) we should only allow schemas with `never` in the context positions

**Comment by mikearnaldi** [comment]
cc @gcanti as the code-owner in question

**Comment by gcanti** [comment]
I'd go for a single parameter
