### ISSUE TITLE
Make parse variants dual

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#1874]
### What is the problem this feature would solve?

The parse functions can't currently be used easily in a pipeable setting, we should be able to do:

```ts
pipe(data, S.parse(schema, options))
```

and

```ts
S.parse(data, schema, options)
```

cc @gcanti as the code owner

### What is the feature you are proposing to solve the problem?

making the parse functions dual

**Comment by gcanti** [comment]
Addressed  in https://github.com/Effect-TS/effect/pull/1842
