### ISSUE TITLE
Add time zone support to `Cron` apis

### ISSUE THREAD

**Issue by fubhy** [Effect-TS/effect#1887]
### What is the problem this feature would solve?

https://github.com/Effect-TS/effect/pull/1884 introduced support for cron expressions. However, there's currently no way to specificy a time zone that the cron schedule should be relative to.

### What is the feature you are proposing to solve the problem?

Add simplistic time zone support if at all possible (we all know how horrible the `Date` API is).

### What alternatives have you considered?

... Skip this and live with the limitation.

The existing cron-like Schedule APIs (e.g. `Schedule.dayOfWeek`) also currently don't support time zones.

If we end up adding this for `Schedule.cron`, we should also add it to those.

**Comment by PaulJPhilp** [comment]
@fubhy I have built a Timezone type for this.  I am testing it now.  Do you have a preference for how it integrates into Cron, dayOfWeek, ...

As an optional parameter to Cron.match, Cron.next, Schedule.dayOf???, ... ?
A chainable (ala moment) Cron.match().timezone("America/NewYork")?

Something else?

**Comment by fubhy** [comment]
> @fubhy I have built a Timezone type for this. I am testing it now. Do you have a preference for how it integrates into Cron, dayOfWeek, ...
> 
> As an optional parameter to Cron.match, Cron.next, Schedule.dayOf???, ... ? A chainable (ala moment) Cron.match().timezone("America/NewYork")?
> 
> Something else?

I think an optional parameter to `Cron.match`, etc. would be good.

**Comment by PaulJPhilp** [comment]
Great.  I’ll have a PR ready in the next few days.

**Comment by aniravi24** [comment]
Restarted the discussion on this: https://discord.com/channels/795981131316985866/1299552735472914443

I was looking to add it as a feature for a library I'm working on, so others can set offsets for cron expressions). I have had that use case where we wanted to easily set a cron to a certain timezone that we were operating in.

**Comment by fubhy** [comment]
We have since added the DateTime module to core. Adding this now should be fairly trivial.

**Comment by fubhy** [comment]
This is actually quite a bit more hairy than I thought. I'll have to take another stab at it...
