### ISSUE TITLE
Add Schema for HashMap and HashSet

### ISSUE THREAD

**Issue by wewelll** [Effect-TS/effect#1954]
### What is the problem this feature would solve?

data structures `HashMap` and `HashSet` don't have a schema

### What is the feature you are proposing to solve the problem?

implement two schemas `S.hashMap` and `S.hashSet` with the same API as `S.readonlyMap` and `S.readonlySet` 

```ts
import { HashMap, HashSet } from 'effect';
import { Schema } from '@effect/schema/Schema';

export const hashMap = <IK, K, IV, V>(
  key: Schema<IK, K>,
  value: Schema<IV, V>
): Schema<ReadonlyArray<readonly [IK, IV]>, HashMap<K, V>> => { ... }

export const hashSet = <I, A>(item: Schema<I, A>): Schema<ReadonlyArray<I>, HashSet<A>> => { ... }
```

**Comment by gcanti** [comment]
closed this as completed in https://github.com/Effect-TS/effect/pull/1922
