### ISSUE TITLE
CLI: `Options.repeated` causes CLI to hang in certain senarios

### ISSUE THREAD

**Issue by ethanniser** [Effect-TS/effect#1973]
### What version of Effect is running?

"@effect/cli": "0.30.5"

### What steps can reproduce the bug?

Im having some issues and ive narrowed it done to `Options.repeated`
```ts
import { Console, Effect } from "effect";
import { BunContext, Runtime } from "@effect/platform-bun";
import { Command, Options } from "@effect/cli";

const repeatedOption = Options.text("repeat").pipe(Options.repeated);

const run = Command.make("test", { repeatedOption }, (args) =>
  Console.log(args)
).pipe(
  Command.run({
    name: "Test",
    version: "1.0.0",
  })
);

const main = Effect.suspend(() => run(globalThis.process.argv));

main.pipe(
  Effect.provide(BunContext.layer),
  Effect.tapErrorCause(Effect.logError),
  Runtime.runMain
);
```

when run with the option, things work as expected:
```
$ tsx test.ts --repeat one --repeat two
{ repeatedOption: [ 'one', 'two' ] }
```

but when no other options or args are included, things *also* work as expected
```
$ tsx test.ts 
Expected to find option: '--repeat'

timestamp=2024-01-25T02:28:43.129Z level=ERROR fiber=#12 cause="Error: {\"_tag\":\"MissingValue\",\"error\":{\"_tag\":\"Paragraph\",\"value\":{\"_tag\":\"Text\",\"value\":\"Expected to find option: '--repeat'\"}}}"
timestamp=2024-01-25T02:28:43.130Z level=ERROR fiber=#12 cause="Error: {\"_tag\":\"MissingValue\",\"error\":{\"_tag\":\"Paragraph\",\"value\":{\"_tag\":\"Text\",\"value\":\"Expected to find option: '--repeat'\"}}}"
```

**however**, including any other args or options causes the cli to just hang forever
```
$ tsx test.ts foo
<HANGS>
^C
$ tsx test.ts --bar
<HANGS>
^C
```

if I remove `Options.repeated`:
```
$ tsx test.ts foo
Expected to find option: '--repeat'

timestamp=2024-01-25T02:30:51.759Z level=ERROR fiber=#12 cause="Error: {\"_tag\":\"MissingValue\",\"error\":{\"_tag\":\"Paragraph\",\"value\":{\"_tag\":\"Text\",\"value\":\"Expected to find option: '--repeat'\"}}}"
timestamp=2024-01-25T02:30:51.760Z level=ERROR fiber=#12 cause="Error: {\"_tag\":\"MissingValue\",\"error\":{\"_tag\":\"Paragraph\",\"value\":{\"_tag\":\"Text\",\"value\":\"Expected to find option: '--repeat'\"}}}"
$ tsx test.ts --bar
Expected to find option: '--repeat'

timestamp=2024-01-25T02:30:53.641Z level=ERROR fiber=#12 cause="Error: {\"_tag\":\"MissingValue\",\"error\":{\"_tag\":\"Paragraph\",\"value\":{\"_tag\":\"Text\",\"value\":\"Expected to find option: '--repeat'\"}}}"
timestamp=2024-01-25T02:30:53.642Z level=ERROR fiber=#12 cause="Error: {\"_tag\":\"MissingValue\",\"error\":{\"_tag\":\"Paragraph\",\"value\":{\"_tag\":\"Text\",\"value\":\"Expected to find option: '--repeat'\"}}}"
```

**Comment by IMax153** [comment]
@ethanniser - I've "fixed" the issue in #1980. 

However, I'd almost argue that the second example _does not_ function as expected. A variadic option created using `repeated` has no `min` or `max` number of times that it must be specified. Therefore, I find it a bit weird that we're throwing an error if we've specified the option 0 times, where it may make more sense for us to return an empty array. This is in contrast to the `atLeast`, `atMost`, and `between` combinators which do specify limits.

@tim-smart - what are your thoughts? Does it make sense to raise an error here? Or should the behavior be adjusted to be akin to marking the option as `withDefault(repeatedOption, [])`?

**Comment by ethanniser** [comment]
> Therefore, I find it a bit weird that we're throwing an error if we've specified the option 0 times, where it may make more sense for us to return an empty array.

I think that causing an error should be the behavior here

Non-repeated options are required by default, and cause an error unless passed to `optional`,
so then I think its confusing for making an option `repeated` to quietly change this behavior, to where no value is suddenly a value

**Comment by IMax153** [comment]
> where no value is suddenly a value

This is the current behavior, however, for `Args.repeated`. Perhaps it would be more clear with some additional documentation? I guess my point is that `Options.repeated` is akin to `Options.atLeast(0)` (for the lower bound of repetitions), so providing no CLI option in theory is "valid".

**Comment by ethanniser** [comment]
it really just comes down to how you encode "no things" vs "one or many things"

`Option<NonEmptyArray<T>>` vs *(potentially empty)* `Array<T>`
`Option.isSome` vs `arr.length > 0`

both are of course "valid", but I think the first is more explicit and follows the behavior of non-variadic options, being required until passed to `optional`

---

At the end of the day, it doesn't matter all that much if its documented and consistent between Options and Args
