### ISSUE TITLE
Type error when using `S.literal` and `S.optional` with `default`

### ISSUE THREAD

**Issue by mrmckeb** [Effect-TS/effect#2002]
### What version of Effect is running?

2.2.2

### What steps can reproduce the bug?

When migrating from `S.optional(...).withDefault(...)`, we hit an issue with `S.literal`. This hasn't been an issue for us with any other types.

This example code block throws a type error on the `default` property.
```ts
const FooSchema = S.literal('a', 'b', 'c');

const MySchema = S.struct({
  foo: S.optional(FooSchema, {
    default: () => 'a',
    // Object literal may only specify known properties, and
    // 'default' does not exist in type '{ readonly as: "Option"; }'.
  }),
});
```

The full error is:
```
No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'default' does not exist in type '{ readonly as: "Option"; }'.ts(2769)
```

We can work around the issue by setting the types as below:
```ts
const FooSchema = S.literal('a', 'b', 'c');
type Foo = S.Schema.To<typeof AstCacheSchema>;

const MySchema = S.struct({
  foo: S.optional<never, Foo, Foo>(FooSchema, {
    default: () => 'a',
  }),
});
```

### What is the expected behavior?

When using `S.literal` with `S.optional`, `as: "Option"` should not be automatically applied.

### What do you see instead?

The error shows that `as: "Option"` is being automatically applied.

### Additional information

TypeScript 5.3.3.

**Comment by gcanti** [comment]
TypeScript errors are a bit cryptic when it comes to overloads (the overload with `as: "Option"` is only the last one attempted by the type checker), here the actual problem is the `default` parameter being inferred as `string` instead of `"a"`, to resolve this you can to add `as const`:

```diff
-default: () => "a"
+default: () => "a" as const
```

**Comment by mrmckeb** [comment]
Thank you!
