### ISSUE TITLE
Tree shaking question

### ISSUE THREAD

**Issue by belgattitude** [Effect-TS/effect#2010]
### What is the problem this feature would solve?

Hey we had issues working with effect in nextjs middleware (edge runtime not supported)... but while digging I realized the tree-shaking wasn't effective. (import * as O from 'effect/Option')

![image](https://github.com/Effect-TS/effect/assets/259798/71241f3d-d52e-47f7-8ffc-ea00d79a4814)

### What is the feature you are proposing to solve the problem?

No idea

**Comment by belgattitude** [comment]
I'll close as it seems to come from one of our internal packages that uses legacy effect-ts/system.

Sorry for the time

**Comment by izakfilmalter** [comment]
@belgattitude Did you find a solution for getting effect working with nextjs edge runtime / middleware?

**Comment by belgattitude** [comment]
I guess it’s possible, you might have to polyfill few node built-ins such as “performance, …” or wait for upcoming nextjs release that includes the latest edge runtime with more node compat: 14.1.1, then cross the fingers

Bundle size is also an issue for the edge, in my case we’re on multiple effect versions. 0.x and 2.x with deps on obsoleted effect packages. I don’t know effect enough, so I just decided to not use in nextjs.
