### ISSUE TITLE
Regression: Allow specifying empty object in Data.TaggedEnum

### ISSUE THREAD

**Issue by johnnywalker** [Effect-TS/effect#2022]
### What version of Effect is running?

2.2.3

### What steps can reproduce the bug?

Use a strict empty object for a child in `Data.TaggedEnum`.

Sample code:

```ts
import { Data } from 'effect'

type Authentication = Data.TaggedEnum<{
  // TS recommends using `Record<string, never>` instead of `{}`
  Anonymous: Record<string, never>
  Authenticated: {
    scope: string
  }
}>
const { Anonymous, Authenticated } = Data.taggedEnum<Authentication>()

const anonymous = Anonymous()
const authenticated = Authenticated({ scope: 'email' })
```

### What is the expected behavior?

`tsc` should compile without error.

### What do you see instead?

`tsc` returns an error:
 
>  Type '{ Anonymous: Record<string, never>; Authenticated: { scope: string; }; }' is not assignable to type '"It looks like you're trying to create a tagged enum, but one or more of its members already has a `_tag` property."'. (lsp)

### Additional information

This worked prior to the regression noted in 2.0.0-next.50: https://github.com/Effect-TS/effect/issues/1556

If you agree that this is a regression, here's a possible fix. Update `ChildrenAreTagged<A>` in [`packages/effect/src/Data.ts`](https://github.com/Effect-TS/effect/blob/a7150736485d4ad4584b383fd482ec0d9b22d94e/packages/effect/src/Data.ts#L295) to:

```ts
type ChildrenAreTagged<A> = keyof A extends infer K
  ? K extends keyof A
  ? '_tag' extends keyof A[K]
  ? A[K]['_tag'] extends never
  ? false
  : true
  : false
  : never
  : never
```

**Comment by tim-smart** [comment]
You should use `Record<string, never>` in a tagged enum declaration, as that is not equivalent to `{}` (an object with no keys).

**Comment by johnnywalker** [comment]
The ESLint rules enabled by `plugin:@typescript-eslint/recommended` includes the `ban-types` rule, and this specifically bans `{}`. I'm no expert in TypeScript internals, so I'll defer to existing discussions.

This comment explains their logic behind banning `{}`: https://github.com/typescript-eslint/typescript-eslint/issues/2063

There is additional discussion here: https://github.com/microsoft/TypeScript/issues/47486. 

If `Record<string, never>` is indeed correct, then we can certainly ignore the rule when using `taggedEnum`.

**Comment by tim-smart** [comment]
If you have to use Record, then the correct type would be `Record<never, never>`.

**Comment by johnnywalker** [comment]
I tested that as well, and it seems `Record<never, never>` is equivalent to `{}`. It allows any non-nullish value.

```ts
// allows any key (does not enforce empty object)
const objectTest: Record<never, never> = { x: 1 }
// allows non-object values
const stringTest: Record<never, never> = "hello"
const boolTest: Record<never, never> = true
const numberTest: Record<never, never> = 1
const arrayTest: Record<never, never> = [1, 2, 3]
// this fails - `null` is not allowed
const fails: Record<never, never> = null
```

**Comment by mikearnaldi** [comment]
While general usage of the type `{}` may be discouraged in this case it is really not an issue, at the end the type you'll work with is `{ _tag: yourTag }` so this is rather an issue with a too strict eslint rule, as Tim suggested if you want to keep such rule you can use `Record<never, never>`
