### ISSUE TITLE
Persisted Cache for preheating on startup

### ISSUE THREAD

**Issue by yuriy-yarosh** [Effect-TS/effect#2042]
### What is the problem this feature would solve?

I'd like to be able to cache requests to 3rd party API's and have a persisted cache across multiple program runs - it could be just a file persisted on disk and restored for in-mem cache preheating. A complete external cache e.g. redis/memcache would deserve a standalone custom implementation, but for preheating support and small frequent requests (e.g. Github API calls, for instance), a persisted file backed one makes perfect sense. 

### What is the feature you are proposing to solve the problem?

It worth making the existing [CacheImpl](https://github.com/Effect-TS/effect/blob/main/packages/effect/src/internal/cache.ts#L294) a bit more modular, so it would accept custom CacheState implementations (with custom initialState) with some form of optional persistence.

### What alternatives have you considered?

Making a custom Persisted Cache from scratch.

It makes sense to Drop [MutableHashMap](https://github.com/Effect-TS/effect/blob/main/packages/effect/src/internal/cache.ts#L218C1-L219C73) out of cache state entirely and replace it with the respective get/set semantics for an external caching, in case of Redis/Memcached, but I'd leave it for in-mem store otherwise.
```
export interface CacheState<in out Key, in out Error, in out Value> {
  map: MutableHashMap.MutableHashMap<Key, MapValue<Key, Error, Value>> /
```

**Comment by mikearnaldi** [comment]
Did you check https://github.com/Effect-TS/effect/blob/2e9bb98d841584eee593b8ed5849c7e012574ccb/packages/experimental/src/RequestResolver.ts#L113 ?

**Comment by yuriy-yarosh** [comment]
@mikearnaldi nope, thanks.
This should work.

... should've asked at Discord instead
