### ISSUE TITLE
When using SchemaTaggedError with Match, I got an Effect.Effect<unknow, unknown, unknown>

### ISSUE THREAD

**Issue by steffanek** [Effect-TS/effect#2049]
### What version of Effect is running?

2.2.3

### What steps can reproduce the bug?

When using SchemaTaggedError with Match, I got an Effect.Effect<unknown, unknown, unknown> see below: 
(either starting the pattern matching with Match.value or Match.type)
```ts
class ProductStatus extends Schema.TaggedClass<ProductStatus>()("ProductStatus", {
  status: Schema.literal("inactive", "active"), 
  cancelledAt: Schema.nullable(Schema.DateFromSelf), 
}){}
class SomeSchemaTaggedError extends Schema.TaggedError<SomeSchemaTaggedError>()("SomeSchemaTaggedError", {}){}
class SomeDataTaggedError extends Data.TaggedClass('SomeDataTaggedError')<{
}> {}

//: Effect.Effect<unknown, unknown, unknown> | ProductStatus | SomeDataTaggedError
//Expected: SomeDataTaggedError | SomeSchemaTaggedError | ProductStatus
const op = pipe(
  Match.value(new ProductStatus({status: "active", cancelledAt: null})),
  Match.not(
    { status: "active" },
    (_) => new SomeDataTaggedError()
  ),
  Match.when(
    { cancelledAt: Match.instanceOf(Date) }, 
    (_) => new SomeSchemaTaggedError()
  ),
  Match.orElse(
    (ps) =>
      new ProductStatus({
        ...ps,
        status: "inactive", 
        cancelledAt: new Date(), 
        })
  )
);
```

### What is the expected behavior?

The type of "op" should be as follow: `SomeDataTaggedError | SomeSchemaTaggedError | ProductStatus`

### What do you see instead?

The type of "op" is as follow: `Effect.Effect<unknown, unknown, unknown> | ProductStatus | SomeDataTaggedError`

### Additional information

The result is the same either when using:
- effect 2.2.2
- @effect/schema 0.61.3

or:
- effect 2.2.3
- @effect/schema 0.61.5

Within discord thread: <https://discord.com/channels/795981131316985866/1203337533078118411>
@tim-smart mentioned: 
> The issue is likely to do with the auto unification code in Match module.

**Comment by mikearnaldi** [comment]
This is very strange:

```ts
import { Schema } from "@effect/schema"
import type { Unify } from "effect"
import { Data } from "effect"

class SomeDataTaggedError extends Data.TaggedError("SomeDataTaggedError")<{}> {}

class SomeSchemaTaggedError extends Schema.TaggedError<SomeSchemaTaggedError>()("SomeSchemaTaggedError", {}) {}

// type X = Effect<unknown, unknown, unknown>
export type X = Unify.Unify<
  SomeSchemaTaggedError
>

// type Y = SomeDataTaggedError
export type Y = Unify.Unify<
  SomeDataTaggedError
>
```

Something is broken with the Schema variant (cc @tim-smart )

**Comment by tim-smart** [comment]
It seems it is because the Schema.TaggedError constructor type is returning a non-interface type, `this` is no longer working.

Will need to do some redesign to get Unify working.

**Comment by tim-smart** [comment]
Or maybe it was the Omit? Just noticed Cause.YieldableError is missing the unify symbols too.
