### ISSUE TITLE
JSONSchema not working as expected with `S.optional`

### ISSUE THREAD

**Issue by mrmckeb** [Effect-TS/effect#2068]
### What version of Effect is running?

effect 2.2.3
@effect/schema 0.61.5

### What steps can reproduce the bug?

`JSONSchema.make()` is a great addition, and works really well overall - thanks again for your hard work on this.

There are two errors I've hit related to `S.optional()`.

1. When creating a JSON schema from a schema using `S.optional()`, I hit this error:
    ```
    Error: cannot build a JSON Schema for `undefined` without a JSON Schema annotation
    ```
    This error does not occur with `{ exact: true }` or `{ default: () => value }`.

2.  Setting default values makes the property `required` in the genearted JSON schema.

This is a working example demonstrating both issues:

```ts
import * as JSONSchema from '@effect/schema/JSONSchema';
import * as S from '@effect/schema/Schema';

const Person = S.struct({
  name: S.string,
  age: S.optional(S.number.pipe(S.description('An optional age.')), {
    default: () => 0,
  }),
  country: S.optional(S.string.pipe(S.description('An optional country.')), {
    // Throws if this is removed.
    exact: true,
  }),
});

const jsonSchema = JSONSchema.make(Person);

console.log(jsonSchema);

```

### What is the expected behavior?

```jsonc
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  // Age is required here, but is actually optional with a default value.
  required: [ 'name', 'age' ],
  properties: {
    name: { type: 'string', description: 'a string', title: 'string' },
    age: {
      type: 'number',
      description: 'An optional age.',
      title: 'number'
    },
    country: {
      type: 'string',
      description: 'An optional country.',
      title: 'string'
    }
  },
  additionalProperties: false
}
```

### What do you see instead?

```jsonc
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [ 'name' ],
  properties: {
    // ...
  },
  additionalProperties: false
}
```

### Additional information

Note that I can make this work with the below, but I then lose any annotations I've added, such as descriptions.
```ts
const jsonSchema = JSONSchema.make(S.from(Person));
```

**Comment by gcanti** [comment]
`JSONSchema.make(schema)` returns a json schema for the `To` type of the provided schema, so in this case:

```ts
{
    readonly name: string;
    readonly age: number;
    readonly country?: string;
}
```

in the type above both `name` and `age` are required so you get `required: [ 'name', 'age' ]` which is correct

**Comment by mrmckeb** [comment]
Hi @gcanti, thanks for the prompt reply.

In our case we need a schema for `from` - as it's a schema for user-supplied data. Perhaps `JSONSchema.make()` could have an option for making the JSON schema using `from` or `to`?

We can make this work by using `S.from(Person)`, however we then lose all annotations from the resulting schema. Do you have any suggestions to get this to work with annotations?

**Comment by gcanti** [comment]
Note that annotations are always added to the `To` side as well, so adding the annotation `S.description('An optional age.')` to the required field `age` is not appropriate.

What you want to do is add an annotation to a schema for user-supplied data (where the `age` field is optional) and then define a transformation that applies a default to the optional field to obtain a required field.

```ts
import * as S from "@effect/schema/Schema"
import * as JSONSchema from "@effect/schema/JSONSchema"

const PersonFrom = S.struct({
  name: S.string,
  age: S.optional(S.number, { exact: true }).pipe(S.propertySignatureAnnotations({ description: "An optional age." })),
  country: S.optional(S.string, { exact: true }).pipe(
    S.propertySignatureAnnotations({ description: "An optional country." })
  )
})

const PersonTo = S.struct({
  name: S.string,
  age: S.number,
  country: S.optional(S.string, { exact: true })
})

const Person = S.transform(
  PersonFrom,
  PersonTo,
  (pf) => ({ ...pf, age: pf.age ?? 0 }),
  (pt) => pt
)

console.log(JSONSchema.make(PersonFrom))
/*
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [ 'name' ],
  properties: {
    name: { type: 'string', description: 'a string', title: 'string' },
    age: {
      type: 'number',
      description: 'An optional age.',
      title: 'number'
    },
    country: {
      type: 'string',
      description: 'An optional country.',
      title: 'string'
    }
  },
  additionalProperties: false
}
*/
```

**Comment by mrmckeb** [comment]
Ah, I see - thanks again!

For our usecase, we're almost always using `@effect/schema` to validate user-supplied data. 

I'll look into how we can do that programatically, as we have a large number of schemas that I'd like to create JSON schemas for.
