### ISSUE TITLE
@effect/schema: does `onExcessProperty` affect encoding as well as decoding?

### ISSUE THREAD

**Issue by liambutler-lawrence** [Effect-TS/effect#2162]
### What is the type of issue?

Documentation is missing, Documentation is confusing

### What is the issue?

We're attempting to migrate from io-ts to @effect/schema. In io-ts, I have a custom wrapper around `t.type` that strips "extra" properties (i.e. properties not specified in the schema) during encoding. This seems equivalent to the built-in `onExcessProperty: 'ignore'` option in @effect/schema; however, the latter is only documented to apply to decoding, not encoding.

1. Does `onExcessProperty` apply to both decoding and encoding, or only to decoding?
2. If the latter, is there a plan to make it apply to encoding as well? What is the current behavior of encoding (ignore, error, preserve)?

My io-ts wrapper type, for clarity:
```
import * as t from 'io-ts'

export const strictType = <P extends t.Props>(props: P): t.TypeC<P> => {
  const baseType = t.type(props)

  return new t.InterfaceType(
    baseType.name,
    baseType.is,
    baseType.validate,
    (a) => {
      const cleanObject: Partial<t.OutputOf<typeof baseType>> = {}
      for (const key in props) {
        cleanObject[key] = props[key]!.encode(a[key])
      }
      return cleanObject as t.OutputOf<typeof baseType>
    },
    props,
  )
}
```

### Where did you find it?

https://github.com/Effect-TS/effect/tree/main/packages/schema#excess-properties

**Comment by gcanti** [comment]
It does apply on both decoding and encoding

```ts
import * as S from "@effect/schema/Schema"

const schema = S.struct({ a: S.NumberFromString })

console.log(S.decodeUnknownSync(schema)({ a: "1", b: 2 })) // => { a: 1 }

console.log(S.encodeUnknownSync(schema)({ a: 1, b: 2 })) // => { a: '1' }
```
