### ISSUE TITLE
Expose `ConfigError` not as a Union but wrapped as Class

### ISSUE THREAD

**Issue by mathiasmaerker** [Effect-TS/effect#2199]
### What version of Effect is running?

2.4

### What steps can reproduce the bug?

Sitting in the beginner workshop, we just spotted this not so nice behaviour
![image](https://github.com/Effect-TS/effect/assets/4051929/9b32c011-1e22-444f-8640-9ca7ad56731e)

### What is the expected behavior?

`ConfigError`should be matchable but only the union elements are catchable

### What do you see instead?

```typescript
.pipe(Effect.catchTag('ConfigError', () => Effect.succeed('bar')))
```

**Comment by jessekelly881** [comment]
Relevant: https://github.com/Effect-TS/effect/issues/1589 (specifically, the overuse of `_tag`)

**Comment by tim-smart** [comment]
Fixed in https://github.com/Effect-TS/effect/pull/2206
