### ISSUE TITLE
Platform/FileSystem: Add a default file system Logger instance 

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/effect#2210]
### What is the problem this feature would solve?

Logging to a file is common enough that it might be useful to have a default file system logger built on top of Platform/FileSystem. Format could be equivalent to Logger.defaultLogger. 

### What is the feature you are proposing to solve the problem?

```ts
import { fileSystemLogger } from "@effect/platform/FileSystem"

const layer = Logger.addScoped(fileSystemLogger("./test.log", { flag: "a+" }))
```

**Comment by mikearnaldi** [comment]
indeed, want to give it a try in a PR?
