### ISSUE TITLE
Add a Schema.config for decoding Configs using a Schema. 

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/effect#2346]
### What is the problem this feature would solve?

It would be convenient to be able to use a Schema instead one of the built in Config primitives for decoding a Config var.  

### What is the feature you are proposing to solve the problem?

Add a `Schema.config :: (Schema<A, string, R>, name?: string) -> Effect<Config<A>, never, R>` function.
### What alternatives have you considered?

None.

**Comment by tim-smart** [comment]
I think this should wait until schema is part of "effect", as it seems like an api that should be owned by the Config module.

**Comment by wewelll** [comment]
I'm using this at the moment : 

```ts
import * as S from '@effect/schema/Schema';
import { EmailAddress } from 'my-domain';

 const EmailAddressConfig = flow(
  Config.string,
  Config.validate({
    message: 'Expected a valid EmailAddress',
    validation: S.is(EmailAddress),
  })
);

const AdminEmailAddressConfig = EmailAddressConfig('ADMIN_EMAIL_ADDRESS');
```

**Comment by mikearnaldi** [comment]
Given we are still not sure about inclusion of `schema` into `effect` due to bundle size optimization we should probably go ahead and implement this in the schema module
