### ISSUE TITLE
Format JSDoc

### ISSUE THREAD

**Issue by steida** [Effect-TS/effect#2395]
### What is the issue?

JSDoc lines are super long and it's not easy to read. Evolu uses `prettier-plugin-jsdoc` and it works well, not sure whether it's suitable for Effect usage.

**Comment by patroza** [comment]
One would have to find a dprint plugin instead.

**Comment by patroza** [comment]
interesting https://github.com/dprint/dprint-plugin-prettier/blob/main/README.md#included-prettier-plugins
