### ISSUE TITLE
Comparison with zod

### ISSUE THREAD

**Issue by rosano** [Effect-TS/effect#2406]
### What is the type of issue?

Something else

### What is the issue?

Would be helpful for newbies like me to document the differences between effect schema and zod (perhaps others too); [this comparison page](https://zod.dev/?id=comparison) could be a useful example. I can make a PR if someone helps me understand.

**Comment by gcanti** [comment]
Regarding the features, the two libraries are on par, `schema` can practically do everything that `zod` can do, albeit with a different syntax (`schema` uses a functional programming style with combinators and transformations, while `zod` provides a chainable API).

The three main differences are:
1. Transformations in `schema` are bidirectional, so it not only decodes like `zod` but also encodes.
2. `schema` is integrated with `Effect` and inherits some benefits from it (such as dependency tracking in transformations).
3. `schema` is highly customizable through annotations, allowing users to attach meta-information.
