### ISSUE TITLE
Stream.paginateChunkEffect should have max_iteration_count

### ISSUE THREAD

**Issue by coleea** [Effect-TS/effect#2437]
### What version of Effect is running?

2.4.15

### What steps can reproduce the bug?

To reproduce issue, clone this repo.
https://github.com/coleea/effect-issue-about-stream

Description :
`Stream.paginateChunkEffect()` loops infinitely if `new PageResult()`'s seconds argument is always false. And finally program crashes because of Heap out of memory error.

![-제목 없음](https://github.com/Effect-TS/effect/assets/7471674/3e48f532-9e66-4cc8-9d5b-b6c42dabd6cd)

### What is the expected behavior?

Yeah, right. this is not bug and this happens by user's mistake. But when this happens, it is hard to find why this error happens. So I think that some detailed description need to be provided.

So I suggest that Program returns Effect.fail() if max_iteration_count exceeds.

For example, `Stream.paginateChunkEffect` takes `max_iteration_count`  as the last argument, or user can skip this argument because default `max_iteration_count` value can be set.

**Comment by mikearnaldi** [comment]
Any default for `max_iteration_count` would be a semantic mistake, we could add a parameter to allow the user to specify a `max_iteration_count` but if such a user specifies it it already means they are on the fence about a potentially infinite loop

**Comment by coleea** [comment]
@mikearnaldi yes. apparently it is not bug. But I hope that there's a way to prevent infinite loops. if `max_iteration_count` is not proper way, timeout or whatever can be alternative solution. I don't know what exactly the best solution is. 

The reason I made this suggestion is that I met this situation and I didn't know why for a while. haha.

if you don't agree with me, it is ok to close issue :)

**Comment by mikearnaldi** [comment]
What you are asking is known in computer science as the Halting Problem of Turing-complete languages, https://en.wikipedia.org/wiki/Halting_problem any solution is semantically incorrect. You already have the ability to set timeouts on any effect you want so I think this is not something we should add, it would be like JS putting a default maximum to a `while(true)`, it would be semantically incorrect.

**Comment by coleea** [comment]
@mikearnaldi After some investigating based on your answer, I think my suggestion is somehow inappropriate. Thank you for answer :) . I'll close this issue.
