### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by ellis** [Effect-TS/effect#2512]
### What is the type of issue?

Something else

### What is the issue?

The Discord invite link appears to be invalid: https://discord.com/invite/hdt7t7jpvn

When I click on it, the error message is: Invite Invalid; This invite may be expired, or you might not have permission to join.

Screenshot:
![image](https://github.com/Effect-TS/effect/assets/97852/c3c5b875-c196-4aaf-a930-5636a89092ef)

### Where did you find it?

- https://github.com/Effect-TS/effect under "Connect with Our Community"
- https://effect.website/docs/guides/scheduling/built-in-schedules in the navbar

**Comment by fubhy** [comment]
Mhm, that's strange. Not sure what would cause that. Glad it worked now.
