### ISSUE TITLE
Support PromiseLike or Effect in `tryPromise` `error`

### ISSUE THREAD

**Issue by leighman** [Effect-TS/effect#2520]
### What is the problem this feature would solve?

In a jest test we are running something like
```
await Effect.runPromise(
      Effect.tryPromise({
        try: () => {
          return Promise.reject(new Error('the error'))
        },
        catch: (e) => {
          if (something) {
             return new BlahFailure()
          }
          throw e
        },
      }),
    )
```
We only want to handle certain cases in the catch and die otherwise.
This example seems to timeout the jest handler.
Are we doing something wrong?

### What is the feature you are proposing to solve the problem?

If the effect handler took a `PromiseLike` then we could return an `async` handler and a rejection could cause an `Exit`?

### What alternatives have you considered?

That jest is messing with us somehow and that `throw`ing is the correct behaviour in this case

**Comment by leighman** [comment]
We seemed to have the same problem when using `Effect.async` to wrap it manually

**Comment by fubhy** [comment]
> We only want to handle certain cases in the catch and die otherwise.

Note that when using `tryPromise` with a catch handler to return typed Errors, you are not actually handling the errors, you are just refining them to be handled elsewhere in your application in a type safe manner.

Throwing in `catch` is odd and I'd avoid that.

If you want to actually handle specific errors, you could use `Effect.catchTag(s)` subsequently.

However, for the purpose of a test, I'd actually do this completely differently and instead match on an `Exit` in your program e.g. using `Effect.matchCause` or by collecting the final Exit value of your entire program and then matching against that (e.g. using `Effect.runPromiseExit`).

**Comment by leighman** [comment]
Yes. I understand I'm only refining them but what if all other cases mean Defect. So you're saying the catch should return `BlahFailure | SomeDefectFlag` and then I should die on `SomeDefectFlag` back in `Effect` land?

**Comment by fubhy** [comment]
There's countless ways to achieve that, e.g. you could refine and use `Cause.UnknownException` (which is what `tryPromise` also uses internally) for the fallback case.

You can then also decide to further elevate that into a defect with a subsequent `flipWith` and `filterOrDie`. Or you can capture all cases in an `Exit` and assert based on that (which is what I usually do).

```ts
Effect.tryPromise({
  try: () => Promise.reject(new Error("foo")),
  catch: (cause) => {
    if (cause instanceof Error && cause.message === "foo") {
      return new MyRefinedError(cause)
    }

    return new Cause.UnknownException(cause)
  }
}).pipe(Effect.flipWith(Effect.filterOrDie(cause => cause instanceof MyRefinedError, identity)))
```

```ts
const exit = await Effect.runPromiseExit(
  Effect.tryPromise({
    try: () => Promise.reject(new Error("foo")),
    catch: (cause) => {
      if (cause instanceof Error && cause.message === "foo") {
        return new MyRefinedError(cause)
      }
  
      return new Cause.UnknownException(cause)
    }
  })
)
```

**Comment by leighman** [comment]
Perfect. Thank you.
No idea why it was hanging jest but without the throw it seems fine.
