### ISSUE TITLE
The "Unifying Return Type" example is not clear

### ISSUE THREAD

**Issue by revosw** [Effect-TS/effect#2537]
### What is the type of issue?

Documentation is confusing

### What is the issue?

In the following sentence, the code example below does not properly convey what "struggles to unify the return type" means
> Unifying Return Type. In situations where TypeScript struggles to unify the returned effect type, Effect.suspend can be employed to resolve this issue. For example:
```ts
import { Effect } from "effect"
 
const ugly = (a: number, b: number) =>
  b === 0
    ? Effect.fail(new Error("Cannot divide by zero"))
    : Effect.succeed(a / b)
 
const nice = (a: number, b: number) =>
  Effect.suspend(() =>
    b === 0
      ? Effect.fail(new Error("Cannot divide by zero"))
      : Effect.succeed(a / b)
  )
```

### Where did you find it?

https://effect.website/docs/guides/essentials/creating-effects

**Comment by revosw** [comment]
🤦‍♂️I have somehow read this far into the documentation without hovering the mouse over any code block, so I didn't realize you could just hover over the symbols to see which type they have!

**Comment by fubhy** [comment]
The difference is the return type (visible on hover over `ugly` and `nice`).

Ugly:
```ts
Effect.Effect<never, Error, never> | Effect.Effect<number, never, never>
```

Nice:
```ts
Effect.Effect<number, Error, never>
```

Unifying, here, means that the two diverging / union return types are merged into one.
