### ISSUE TITLE
Misleading error message in Http Client

### ISSUE THREAD

**Issue by acron0** [Effect-TS/effect#2630]
https://github.com/Effect-TS/effect/blob/027418edaa6aa6c0ae4861b95832827b45adace4/packages/platform/src/internal/http/client.ts#L264

IIUC this error message isn't connected to "non 2xx" status codes necessarily, simply that the `filterStatus` predicate call returned `false`. As an addendum, I have always found it very unhelpful that this error message doesn't include the _actual_ status code, so I would propose that any message which indicates that a status code check failed _should_ include what the status code actually was.

**Comment by tim-smart** [comment]
All response errors include the actual status code in the message, see: https://github.com/Effect-TS/effect/blob/027418edaa6aa6c0ae4861b95832827b45adace4/packages/platform/src/Http/ClientError.ts#L60

Will make the error message more generic however, as yes the predicate doesn't guarantee the status is in the 2xx range.
