### ISSUE TITLE
Effect.forEach inference sometimes fails

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#2639]
The following fails to infer, it works when `HashSet.union` is removed or extracted

```ts
import { Effect, HashSet } from "effect"

const f = (n: number) => n

Effect.forEach(
  HashSet.union(
    HashSet.make(0, 1, 2),
    HashSet.make(0, 1, 2)
  ),
  (n) => Effect.succeed(f(n))
)
```

**Comment by mikearnaldi** [comment]
This is due to #2608 so @patroza , removing NonEmpty overloads fixes it, maybe we have to use `X extends Iterable` and then differentiate instead of using overloads

**Comment by patroza** [comment]
> This is due to #2608 so @patroza , removing NonEmpty overloads fixes it, maybe we have to use `X extends Iterable` and then differentiate instead of using overloads

https://github.com/Effect-TS/effect/commit/d98aafd65f4a6d8625998867f033e7bc74bc0f82 seems to fix it
