### ISSUE TITLE
Improve dev DX in Next.js

### ISSUE THREAD

**Issue by steida** [Effect-TS/effect#2701]
### What is the problem this feature would solve?

Related https://vercel.com/blog/how-we-optimized-package-imports-in-next-js

Effect lib should be part of this list:

https://github.com/vercel/next.js/blob/c9291d6dd57e08c525733b7187a3b4256bc5f8af/packages/next/src/server/config.ts#L833

I suppose they would happily accept PR for that. 

### What is the feature you are proposing to solve the problem?

Faster dev mode

**Comment by mikearnaldi** [comment]
closed by https://github.com/vercel/next.js/pull/65465
