### ISSUE TITLE
sql: Silently swallows errors

### ISSUE THREAD

**Issue by TheDevMinerTV** [Effect-TS/effect#2730]
### What version of Effect is running?

3.1.3

### What steps can reproduce the bug?

1. Set up a PostgreSQL container
2. Run the following code (make sure that the connection credentials are incorrect)
```ts
import * as Sql from "@effect/sql";
import * as Pg from "@effect/sql-pg";
import { Config, Effect } from "effect";

const SqlLive = Pg.client.layer({ database: Config.succeed("inventory") });

const program = Effect.gen(function* () {
  yield* Effect.log("Connecting to SQL...");
  const sql = yield* Sql.client.Client;
  yield* Effect.log("Connected to SQL!");

  const people = yield* sql<{
    readonly id: number;
    readonly name: string;
  }>`SELECT id, name FROM people`;
  // Hangs here ^

  yield* Effect.log(`Got ${people.length} results!`);
}).pipe(Effect.scoped);

program.pipe(Effect.provide(SqlLive), Effect.runPromise);
```

### What is the expected behavior?

The error gets logged, or gets returned up.

### What do you see instead?

Nothing from the Effect code, but my PostgreSQL server is spitting out authentication errors.

### Additional information

```json
    "@effect/sql": "^0.2.5",
    "@effect/sql-pg": "^0.2.5",
```

**Comment by TheDevMinerTV** [comment]
Apparently it's also happening with the migrator which also silently hangs the application when the migrations folder doesn't exist.

**Comment by tim-smart** [comment]
Hmm I tried your example and got this:

<img width="939" alt="image" src="https://github.com/Effect-TS/effect/assets/40680/a3fec6d9-9cff-43bf-a755-ff226e31fa08">

**Comment by tim-smart** [comment]
I tried your example and got this error:

<img width="1030" alt="image" src="https://github.com/Effect-TS/effect/assets/40680/2ff0d6a6-848e-426a-bf15-519f14a79bea">

**Comment by TheDevMinerTV** [comment]
Is there a environment variable to change the log level?

**Comment by mikearnaldi** [comment]
@TheDevMinerTV is this related to the discord discussion? if yes then this is not an issue, if not we need a full repro

**Comment by thanhnguyen2187** [comment]
A bit of digging led me to `FileSystem.ts` and `loadFromFileSystem`:

```ts
export const fromFileSystem = (directory: string): Loader<FileSystem> =>
  FileSystem.pipe(
    Effect.flatMap((FS) => FS.readDirectory(directory)),
    Effect.mapError((error) => new MigrationError({ reason: "failed", message: error.message })),
    Effect.map((files): ReadonlyArray<ResolvedMigration> =>
      files
        .map((file) => Option.fromNullable(file.match(/^(?:.*\/)?(\d+)_([^.]+)\.(js|ts)$/)))
        .flatMap(
          Option.match({
            onNone: () => [],
            onSome: ([basename, id, name]): ReadonlyArray<ResolvedMigration> =>
              [
                [
                  Number(id),
                  name,
                  Effect.promise(
                    () =>
                      import(
                        /* @vite-ignore */
                        `${directory}/${basename}`
                      )
                  )
                ]
              ] as const
          })
        )
        .sort(([a], [b]) => a - b)
    )
  )
```

I think we should have some docs for this :sweat_smile:

**Comment by thanhnguyen2187** [comment]
I tried putting invalid TypeScript syntax within a migration file, and it does not get picked up either. Seems like `Effect.promise` from the file above is the problem? The docs said that:

> promise
>
> This constructor is similar to a regular Promise, where you're confident that the asynchronous operation will always succeed. It allows you to create an Effect that represents successful completion without considering potential errors. However, it's essential to ensure that the underlying Promise never rejects.

**Comment by thanhnguyen2187** [comment]
I dug through the code and found that the default migration table is `effect_sql_migrations`. I got

```
SqliteError: no such table: effect_sql_migrations
```

From querying the table, which means `MigratorLive` doesn't run, even after it was provided? It seems weird, as when I provide a non-existent migration folder path, it did raise an error

```
MigrationError: ENOENT: no such file or directory, scandir '...'
```

**Comment by thanhnguyen2187** [comment]
I found the problem: I was using `Effect.map` in my `.ts` migration file, while `Effect.flatMap` is needed :sweat:. My case is done here then

**Comment by risjai** [comment]
@TheDevMinerTV check this out - https://github.com/Effect-TS/effect/pull/3861

**Comment by risjai** [comment]
@TheDevMinerTV I hope we are looking for something like this w.r.t my above comment.
```
import * as Sql from "@effect/sql";
import * as Pg from "@effect/sql-pg";
import { Config, Effect, Console } from "effect";

const SqlLive = Pg.client.layer({ database: Config.succeed("inventory") });
const program = Effect.gen(function* (_) {
  yield* Effect.logInfo("Attempting to connect to SQL...");

  const sql = yield* Sql.client.Client.pipe(
    Effect.tapError((e) => Effect.logError(`SQL Connection Error: ${e}`))
  );

  yield* Effect.logInfo("Connected to SQL!");
  const people = yield* sql<{
    readonly id: number;
    readonly name: string;
  }>`SELECT id, name FROM people`;


  yield* Effect.logInfo(`Got ${people.length} results!`);
}).pipe(
  Effect.catchAll((error) => 
    Effect.logError(`Program Error: ${error}`).pipe(
      Effect.zipRight(Effect.fail(error))
    )
  ),
  Effect.scoped
);

program.pipe(
  Effect.provide(SqlLive),
  Effect.catchAllCause((cause) => 
    Console.error(`Fatal Error: ${cause}`)
  ),
  Effect.runPromise
);
```

**Comment by risjai** [comment]
@omarsoufiane how do we conclude this? There isn't going to be any check-in for this.

**Comment by mikearnaldi** [comment]
closing this as there is no bug repro, if anyone has a reproduction please open a new issue
