### ISSUE TITLE
Service members from Effect.Tag not behaving like normal effects

### ISSUE THREAD

**Issue by arekmaz** [Effect-TS/effect#2745]
### What version of Effect is running?

3.1.4

### What steps can reproduce the bug?

given this initial code:
```typescript
import { Effect } from "effect";

class LoaderArgs extends Effect.Tag("@services/LoaderContext")<
  LoaderArgs,
  { context: number }
>() {}

```

the `LoaderArgs.context` is correctly typed as an effect in typescript, and in runtime is present (a function is shown)

however, I cannot do `LoaderArgs.context.pipe(...` as it throws a runtime exception ("cannot find 'pipe' in undefined")

also this code fails:

```typescript
Effect.runSync(
  Effect.map(LoaderArgs.context, (ctx) => console.log({ ctx })).pipe(
    Effect.provideService(LoaderArgs, { context: 5 }),
  ),
);
```

also this code fails:

```typescript
Effect.runSync(
  Effect.flatMap(LoaderArgs.context, (ctx) => {
    console.log({ ctx });
    return Effect.void;
  }).pipe(Effect.provideService(LoaderArgs, { context: 5 })),
);

```

with this error:
<img width="1056" alt="image" src="https://github.com/Effect-TS/effect/assets/24407822/a7cadebf-ab36-4836-84be-26b81d32eabb">

my small repro is in bun, but I first encountered it with node

also, the following ways of expressing the same code work:

```typescript
Effect.runSync(
  Effect.map(LoaderArgs, ({context: ctx}) => console.log({ ctx })).pipe(
    Effect.provideService(LoaderArgs, { context: 5 }),
  ),
);

```

and

```typescript
Effect.runSync(
  LoaderArgs.pipe(
    Effect.map(({ context: ctx }) => console.log({ ctx })),
    Effect.provideService(LoaderArgs, { context: 5 }),
  ),
);

```

### What is the expected behavior?

the code should work (not throw) as with Effect.Tag member services should just be plain effects which work with every mode of map, flatMap etc...

### What do you see instead?

![image](https://github.com/Effect-TS/effect/assets/24407822/61c6f147-baa6-4a45-a996-8d7541c5d930)

**Comment by mikearnaldi** [comment]
Yeah it is a name clash, unfortunately Tag already have some members, wondering if we can issue a type error in such cases
