### ISSUE TITLE
Github sidebar link outdated

### ISSUE THREAD

**Issue by THOUSAND-SKY** [Effect-TS/effect#2800]
### What is the type of issue?

Documentation is confusing

### What is the issue?

The sidebar on the github repo points to https://effect-ts.github.io/effect/ , dunno if that's intended, I would've expected to find the link to https://www.effect.website/ there.

### Where did you find it?

https://github.com/Effect-TS/effect sidebar 'About' section

**Comment by gcanti** [comment]
Changed to `https://www.effect.website`, thanks.
