### ISSUE TITLE
SubscriptionRef.fromStream or Stream.runIntoSubscriptionRef

### ISSUE THREAD

**Issue by dilame** [Effect-TS/effect#2818]
### What is the problem this feature would solve?

I have a stream of values and i want to be able to subscribe to this stream and instantly receive the latest value from it + all subsequent updates

### What is the feature you are proposing to solve the problem?

`SubscriptionRef.fromStream` function – it takes the `Stream` as input and returns a `SubscriptionRef`.
Or from the other side - `Stream.runIntoSubscriptionRef`

**Comment by dilame** [comment]
As i understand – it probably will not be added to library, so for folks came here from google, a possible solution
```ts
import { Cause, Effect, Scope, Sink, Stream, SubscriptionRef } from "effect"

export const toSubRef = <A, R>(
  stream: Stream.Stream<A, never, R>,
): Effect.Effect<
  SubscriptionRef.SubscriptionRef<A>,
  Cause.NoSuchElementException,
  R | Scope.Scope
> =>
  Effect.gen(function* () {
    const [head, rest] = yield* Stream.peel(stream, Sink.head())
    const ref = yield* SubscriptionRef.make(yield* head)
    yield* Stream.runForEach(rest, item => SubscriptionRef.set(ref, item)).pipe(
      Effect.forkScoped,
      Effect.interruptible,
    )
    return ref
  })
```

**Comment by tim-smart** [comment]
Yes, this is not something we will add officially :)
