### ISSUE TITLE
`ReadableStream.cancel()` doesn't interrupt ongoing Effects with `Stream.toReadableStream`

### ISSUE THREAD

**Issue by mattrossman** [Effect-TS/effect#2828]
### What version of Effect is running?

3.2.4 (assuming Playground is using latest)

### What steps can reproduce the bug?

Create a Stream that invokes some async effects internally. Convert it to a ReadableStream with `Stream.toReadableStream`. Get a reader for the stream with `ReadableStream.getReader()` and start reading the stream to process the async effects. Cancel the reader partway through execution of a read. The stream will stop reading new elements, however ongoing effects continue execution.

Playground: https://effect.website/play#9UOxTEJF4YgHoFqrVz3io

### What is the expected behavior?

I expect cancelling the `ReadableStreamDefaultReader` will interrupt ongoing effects inside the stream.

For comparison, here is a playground that does not use `Stream.toReadableStream`. Note that interrupting the `Stream.runDrain` effect correctly interrupts the stream's internal effects, so "After input 2" is not printed.

https://effect.website/play#sesV2aA8nP4En4jUjmhU

### What do you see instead?

Cancelling the reader prevents new elements from being produced, but ongoing effects continue execution in the background. Notice "After input 2" is printed after the ReadableStream has been cancelled.

### Additional information

The root of the issue seems to be that this `Effect.runPromise` call is not provided an `AbortSignal` to interrupt it.
https://github.com/Effect-TS/effect/blob/1262e7b182788c44167c20ed3c9fbb99ebb76208/packages/effect/src/internal/stream.ts#L6590-L6592

I was able to work around this myself by copying the source code of `Stream.toReadableStream` and adding an `AbortController`, providing its signal to `runPromise` and calling `.abort()` on it inside of the `cancel()` callback.

```tsx
const pullController = new AbortController()

// ...

pull() {
  return runPromise(pull, { signal: pullController.signal })
}
cancel() {
  pullController.abort()
  return Effect.runPromise(Scope.close(scope, Exit.void))
}
```

**Comment by tim-smart** [comment]
Fixed in above PR: https://effect.website/play#1d39871a24b5
