### ISSUE TITLE
CLI Wizard Displays Incorrect Output for Optional Choices

### ISSUE THREAD

**Issue by gcanti** [Effect-TS/effect#2831]
### What version of Effect is running?

@effect/cli@0.36.34

### What steps can reproduce the bug?

The CLI wizard incorrectly displays the output for optional choice parameters. Instead of showing a clear and user-friendly way to indicate a lack of selection (`None`), it outputs a JSON-like string which is not intuitive for end-users.

1. Create a TypeScript file named `repro.ts` with the following content:
    ```ts
    import { Command, Options } from "@effect/cli"
    import { NodeContext, NodeRuntime } from "@effect/platform-node"
    import { Console, Effect } from "effect"

    const opt = Options.choice("a", ["b", "c"]).pipe(Options.optional)
    const command = Command.make("hello-world", { opt }, ({ opt }) => Console.log(opt))
    const cli = Command.run(command, {
      name: "Hello World CLI",
      version: "v1.0.0"
    })
    Effect.suspend(() => cli(process.argv)).pipe(
      Effect.provide(NodeContext.layer),
      NodeRuntime.runMain
    )
    ```
2. Run the command in a terminal:
    ```sh
    npx tsx repro.ts --wizard
    ```

### What is the expected behavior?

The CLI wizard should present a clear and user-friendly method to indicate that no option was selected.

### What do you see instead?

The output displayed is `Default ['{"_id":"Option","_tag":"None"}']?`, which appears to be a raw serialization of the internal state rather than a user-friendly message or indication.

### Additional information

Output:

```
% npx tsx repro.ts --wizard
Wizard Mode for CLI Application: Hello World CLI (v1.0.0)

Instructions

  The wizard mode will assist you with constructing commands for Hello World CLI (v1.0.0).

  Please answer all prompts provided by the wizard.

COMMAND: hello-world

Options Wizard - hello-world

? -a b | c
  
    One of the following: b, c
  
  This option is optional - use the default? › 
❯ Default ['{"_id":"Option","_tag":"None"}'] 
  Custom 
```

**Comment by IMax153** [comment]
Closed by #2847.
