### ISSUE TITLE
@effect/schema MessageAnnotation type doesn't allow to use dependencies

### ISSUE THREAD

**Issue by dilame** [Effect-TS/effect#2846]
### What version of Effect is running?

3.2.5

### What steps can reproduce the bug?

```ts
import { Schema } from '@effect/schema';
import { Effect } from 'effect';

Schema.message(() =>
  Effect.gen(function* () {
    const i18n = yield* I18nContextTag;
    return i18n.t('message');
  }),
);
```

### What is the expected behavior?

In the [documenation](https://github.com/Effect-TS/effect/blob/main/packages/schema/README.md#effectful-messages) written 

> Messages are not only of type string but can return an Effect so that they can have dependencies

### What do you see instead?

<img width="759" alt="Screenshot 2024-05-24 at 20 23 46" src="https://github.com/Effect-TS/effect/assets/9336742/e6dd7389-e52f-4c9d-b497-3fe11cfbca4f">

```

Type Effect<string, never, I18nContextTag> is not assignable to type

string | Effect<string, never, never> | {   readonly message: string | Effect<string, never, never>;   readonly override: boolean; }

Type Effect<string, never, I18nContextTag> is not assignable to type Effect<string, never, never> with 'exactOptionalPropertyTypes: true'. Consider adding undefined to the types of the target's properties.

Type I18nContextTag is not assignable to type never

```

### Additional information

Because the types are 

```ts
export type MessageAnnotation = (
  issue: ParseIssue
) => string | Effect<string> | {
  readonly message: string | Effect<string>
  readonly override: boolean
}
```

**Comment by gcanti** [comment]
This is intentional, you need a default. In the documentation, there's an example using `Effect.serviceOption`: https://github.com/Effect-TS/effect/tree/70001732f4b04678772249377f06dbe448f15d6c/packages/schema#effectful-messages
