### ISSUE TITLE
`@effect/platform`s `ClientRequest` (and possibly others) don't parse input urls

### ISSUE THREAD

**Issue by datner** [Effect-TS/effect#2877]
### What version of Effect is running?

latest

### What steps can reproduce the bug?

```ts
HttpClient.request.get(new URL("https://google.com?q=something")).pipe(
  HttpClient.request.setUrlParams(HttpClient.urlParams.empty),
  HttpClient.request.appendUrl("/something")
)
```

### What is the expected behavior?

a request to `http://google.com/something`

### What do you see instead?

a request to `http://google.com?q=something/something`

### Additional information

:(

**Comment by datner** [comment]
@tim-smart It's still impossible to _remove_ url params or reset them like the example above is attempting to, maybe `setUrlParams` is not the right one and should keep it's `appendAll`-kind approach, but we might want a `replaceUrlParams` or something... 🤔 

Please re-open 🙏🏻

**Comment by tim-smart** [comment]
Sounds like a different issue, can you open another one?
