### ISSUE TITLE
JSR computability

### ISSUE THREAD

**Issue by hemedani** [Effect-TS/effect#2918]
### What is the problem this feature would solve?

[added to jsr](https://jsr.io/)

### What is the feature you are proposing to solve the problem?

[added to jsr](https://jsr.io/)

**Comment by fubhy** [comment]
https://discord.com/channels/795981131316985866/795983589644304396/1214523530721366046

This has been discussed before at multiple occasions and so far the consensus is that we don't intend to publish to jsr.io in the foreseeable future.
