### ISSUE TITLE
`Struct.evolve` no compile time error for non function transformers

### ISSUE THREAD

**Issue by kristiannotari** [Effect-TS/effect#2953]
### What is the problem this feature would solve?

Coming from the archived repository, I was suggesting to make some adjustments to the `Struct.evolve` function in order for it to spot some cases where right now it errors at runtime instead of compile time.

- effect version `3.3.0`
- [old issue](https://github.com/Effect-TS/data/issues/376)

repro:
```ts
const mystruct = { a: 42, b: `hello` }
const bad = Struct.evolve(mystruct, Record.fromEntries([[`a`, `not a function`]])) // not an error ❌
```

### What is the feature you are proposing to solve the problem?

Adjusting of the `Struct.evolve` type signature to actively check for the transformation object.

Suggested solution (at least works for me, of course not well battle tested):
```ts
type Transformed<O, T> = unknown & {
    [K in keyof O]: K extends keyof T ? (T[K] extends (...a: any) => any ? ReturnType<T[K]> : O[K]) : O[K]
}
type PartialTransform<O, T> = {
    [K in keyof T]: T[K] extends (a: O[K & keyof O]) => any ? T[K] : (a: O[K & keyof O]) => unknown
}

export const evolve: {
    <O, T>(t: PartialTransform<O, T>): (obj: O) => Transformed<O, T>
    <O, T>(obj: O, t: PartialTransform<O, T>): Transformed<O, T>
} = Struct.evolve


const mystruct = { a: 42, b: `hello` }
const bad = Struct.evolve(mystruct, Record.fromEntries([[`a`, `not a function`]])) // not an error ❌
const good = evolve(mystruct, Record.fromEntries([[`a`, `not a function`]])) // compile error ✅
```

Notice this is allowing for compile time known / typed transformations object with no overlapping with original struct properties.

That is:
```ts
const actual = Struct.evolve(mystruct, { c: () => 42 }) // compile error ✅
const regression = evolve(mystruct, { c: () => 42 }) // not an error ❌
```

This last corner case / regression may be solvable though.

**Comment by jessekelly881** [comment]
Lgtm as well. :) I created a PR with both of your changes. #2954
