### ISSUE TITLE
Cli: --log-level flag

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/effect#2978]
It would be nice if @effect/cli generated a --log-level flag that set Logger.withMinimumLogLevel w/in the context of the cli commands. It's not too tedious to write by hand but seems general enough to be available for all cli applications.

**Comment by mikearnaldi** [comment]
cc @IMax153

**Comment by IMax153** [comment]
@jessekelly881 - should this be a built-in command? Or an option you can choose to use from the CLI package. 

I'm thinking it should be a built-in.

**Comment by jessekelly881** [comment]
I also think it would make sense to be built in. I can't think of a compelling reason why you wouldn't want to provide the option but I wonder if it makes sense to be able to modify the default.
