### ISSUE TITLE
Effect no longer works in cloudflare workers

### ISSUE THREAD

**Issue by Mkassabov** [Effect-TS/effect#3057]
### What version of Effect is running?

3.4.0

### What steps can reproduce the bug?

1. use effect in a cloudflare worker.
2. attempt to run a cloudflare worker.
3. cloudflare worker crashes

### What is the expected behavior?

cloudflare worker not crashing

### What do you see instead?

cloudflare worker crashes with the following error:
```
✘ [ERROR] service core:user:orange-dust-2f93: Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/

    at null.<anonymous> (index.js:7385:102)
    at null.<anonymous> (index.js:7382:18)
    at null.<anonymous> (index.js:171:25) in globalValue
    at null.<anonymous> (index.js:7379:36) in envRefMake
    at null.<anonymous> (index.js:7385:46)


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

### Additional information

We were migrating off effect 3.3.1
This seems be occurring because effect 3.4.0 hoists a `new AbortController()` to the global scope. Cloudflare doesn't support abort controllers in the global scope apparently.

Provided are 2 examples, one where effect is used, and one where just a normal `AbortController` is used in the global scope, both have the same error. In the examples the error is not obvious through the stack-trace; we run our own build pipelines for cloudflare workers so we can see the exact (compiled) line:

```
var currentAbortController = /* @__PURE__ */ envRefMake("effect/Micro/currentAbortController", () => new AbortController());
```

It's possible effect hoists other things that cause problems and this is just the first thing that gets hit. I'm not too familiar with the 3.3.1 to 3.4 changes

Reproduction here:
just `pnpm install` & `pnpm dev` to run

- `npm create cloudflare@latest` + effect https://github.com/Mkassabov/orange-dust-2f93
- `npm create cloudflare@latest` + global abort controller https://github.com/Mkassabov/orange-dust-2f93/tree/no-effect-abort-controller.

**Comment by mikearnaldi** [comment]
@tim-smart maybe we can use a custom type instead of AbortController?
