### ISSUE TITLE
Unsupported schema Error while applying Partial to Schema class

### ISSUE THREAD

**Issue by bhvngt** [Effect-TS/effect#3113]
### What version of Effect is running?

3.4.3

### What steps can reproduce the bug?

```typescript
import { Schema } from "@effect/schema";

class Todo extends Schema.Class<Todo>("Todo")({
  id: Schema.Number,
  title: Schema.String,
  completed: Schema.Boolean
}) {}

const CreateTodoParams = Todo.pipe(Schema.omit("id"));
type CreateTodoParams = Schema.Schema.Type<typeof CreateTodoParams>;

const UpdateTodoParams = Schema.partial(Todo, { exact: true }); // throws Unsupported schema schema (Transformation): (Todo (Encoded side) <-> Todo)
type UpdateTodoParams = Schema.Schema.Type<typeof UpdateTodoParams>;

```

### What is the expected behavior?

It should not throw any error. Also it is unionising properties with `undefined` for `UpdateTodoParams` to 

```typescript
const UpdateTodoParams: Schema.SchemaClass<{
readonly id?: number | undefined;
readonly title?: string | undefined;
readonly completed?: boolean | undefined;
}, {
readonly id?: number | undefined;
readonly title?: string | undefined;
readonly completed?: boolean | undefined;
}, never>
```
even though `{exact: true}` is passed. My understanding is that it should opt-out of that.

### What do you see instead?

See following error in the terminal

```
Unsupported schema
schema (Transformation): (Todo (Encoded side) <-> Todo)
	at Module.partial ./node_modules/.pnpm/@effect+schema@0.68.10_effect@3.4.3/node_modules/@effect/schema/src/AST.ts:2245
	at Module.apply ./node_modules/.pnpm/@effect+schema@0.68.10_effect@3.4.3/node_modules/@effect/schema/src/Schema.ts:2855
	at Module.<anonymous> ./node_modules/.pnpm/effect@3.4.3/node_modules/effect/src/Function.ts:85
```

**Comment by gcanti** [comment]
It raises an error because the `Schema.Class` API implicitly defines a transformation, specifically from:

```ts
Schema.Struct({
  id: Schema.Number,
  title: Schema.String,
  completed: Schema.Boolean
})
```

to `Todo` in this case, and transformations are not supported by `Schema.partial`.

However, this should work:

```ts
const UpdateTodoParams = Schema.partial(Schema.Struct(Todo.fields), { exact: true })
```

**Comment by bhvngt** [comment]
Got it. Thank you for your reply. 

Tried your solution and that stopped the error from occurring. However, I was expecting the non-unionised type, since `exact: true` is passed as an option to opt out of unionisation. However, types are still unionised. Am I missing something here?

<img width="647" alt="image" src="https://github.com/Effect-TS/effect/assets/79074469/784c88da-990e-4650-9192-54e7e65c6eb3">

**Comment by gcanti** [comment]
Do you have the `exactOptionalPropertyTypes` option enabled in your tsconfig?

**Comment by bhvngt** [comment]
Yep that was the missing piece. Sorry, I overlooked the documentation [here](https://github.com/Effect-TS/schema#requirements). 

Thanks you very much for this really powerful and composable library.
