### ISSUE TITLE
Data.Error/TaggedError swallows cause when logged

### ISSUE THREAD

**Issue by johtso** [Effect-TS/effect#3127]
### What version of Effect is running?

3.4.5

### What steps can reproduce the bug?

https://effect.website/play#60bb9fa16ff5

### What is the expected behavior?

Should render the same as a vanilla Error including causes

### What do you see instead?

No cause information

**Comment by dilame** [comment]
There is a proper implementation of custom error classes using `extend`, i worked on it it several years ago

https://github.com/adriengibrat/ts-custom-error/blob/main/src/custom-error.ts#L27-L47

**Comment by johtso** [comment]
This is really making it hard to debug issues. I wonder if there's some kind of temporary workaround?

**Comment by johtso** [comment]
Related: https://github.com/Effect-TS/effect/issues/1651

**Comment by johtso** [comment]
@tim-smart I see you added a few of the methods to the `YieldableError` class. Can you shed any light on why it's been accumulating these custom methods rather than just leaving the standard methods of the `Error` that it extends?

Would it not make more sense for the behaviour to match a vanilla Error as closely as possible unless there's a specific reason to diverge? Is there a reason that I'm missing?

**Comment by tim-smart** [comment]
We made `YieldableError` extend `Inspectable` which adds those methods.

I have found a way to get `cause` to render, while preserving the custom `.toString` behaviour.

We can't remove those methods until the next major version, if that is something we decide to do.

**Comment by johtso** [comment]
@tim-smart do you think it would make sense to open a separate issue regarding displaying of causes of unhandled yielded errors and errors logged with `Effect.logError`?
