### ISSUE TITLE
Simplify `Schema.TaggedRequest` Signature for Better Usability and Readability

### ISSUE THREAD

**Issue by gcanti** [Effect-TS/effect#3144]
### What is the problem this feature would solve?

The current signature of `Schema.TaggedRequest` is difficult to parse, which may lead to confusion and errors in its usage. The syntax for declaring a `TaggedRequest` involves multiple parameters that can be challenging to understand and maintain.

### Current Syntax

Here is the current way `TaggedRequest` is implemented:

```ts
class Sample extends Schema.TaggedRequest<Sample>()(
  "Sample",
  Schema.String,
  Schema.Number,
  { id: Schema.String, foo: Schema.Number }
) {}
```

### Proposed Changes

To enhance clarity and ease of use, I propose restructuring the `TaggedRequest` parameters into an object:

```ts
class Sample extends Schema.TaggedRequest<Sample>()(
  "Sample",
  {
    failure: Schema.String,
    success: Schema.Number,
    payload: { 
      id: Schema.String, 
      foo: Schema.Number 
    }
  }
) {}
```

**Comment by HpyBara** [comment]
Also a little bit confusing when switching from TaggedClass to TaggedRequest that Success and Failure/Error in different order.

**Comment by mikearnaldi** [comment]
We might be able to do this in a backward compatible manner as the two signatures can be differentiated via overloads

**Comment by mikearnaldi** [comment]
Also why are we doubling up "Sample" ? can't we use a single tag by default and have id = tag?

**Comment by gcanti** [comment]
> can't we use a single tag by default and have id = tag?

ah yeah, it already works like that, I don't remember where I got the example from, I'll fix it
