### ISSUE TITLE
Schema.Capitalize

### ISSUE THREAD

**Issue by mabasic** [Effect-TS/effect#3189]
### What is the problem this feature would solve?

I want to capitalize a string during schema transformation.

Considering that `Schema.Lowercase` and `Schema.Uppercase` exist, I think that `Schema.Capitalize` should exist also. `String` already has methods for `capitalize` and `uncapitalize`.

### What is the feature you are proposing to solve the problem?

It should allow for string capitalization transformation.

### What alternatives have you considered?

```
const trimLowercaseCapitalizeSchema = compose(
  Schema.Trim,
  Schema.Lowercase,
).pipe(
  Schema.transform(Schema.String, {
    decode: String.capitalize,
    encode: String.uncapitalize,
  }),
);
```

**Comment by datner** [comment]
It should be noted that the `Lowercase` and `Uppercase` api encode using `identity`. By extension we might want `Capitalize` and `Uncapitalize` instead of `Capitalize` with encoding to `.uncapitalized`
