### ISSUE TITLE
RuntimeException: Cannot execute an Effect versioned 3.5.6 with a Runtime of version 3.4.7

### ISSUE THREAD

**Issue by cschroeter** [Effect-TS/effect#3308]
### What version of Effect is running?

3.5.6

### What steps can reproduce the bug?

I have a Next.js deployment at [https://github.com/cschroeter/park-ui/tree/main/website](https://github.com/cschroeter/park-ui/tree/main/website) using the following dependencies:

```json
{
  "dependencies": {
    "@effect/platform": "0.59.2",
    "@effect/schema": "0.68.26",
    "effect": "3.5.6"
  }
}
```
The error only appears on Vercel.

### What is the expected behavior?

Not to see any RuntimeException

### What do you see instead?

```bash
⨯ (FiberFailure) RuntimeException: Cannot execute an Effect versioned 3.5.6 with a Runtime of version 3.4.7
    at /var/task/website/.next/server/chunks/76767.js:3:111012
 ```

### Additional information

Example code:

```jsx
await Effect.runPromise(
    pipe(
      Effect.fromNullable(searchParams.get('order_id')),
      Effect.flatMap((orderId) =>
        pipe(
          HttpClientRequest.get(`https://api.lemonsqueezy.com/v1/orders/${orderId}`, {
            headers: {
              Accept: 'application/vnd.api+json',
              'Content-Type': 'application/vnd.api+json',
              Authorization: `Bearer ${LEMON_SQUEEZY_API_KEY}`,
            },
          }),
          HttpClient.fetchOk,
          HttpClientResponse.schemaBodyJsonScoped(Order),
          Effect.timeout('1 seconds'),
          Effect.retry(Schedule.exponential(200).pipe(Schedule.compose(Schedule.recurs(3)))),
        ),
      ),
      Effect.map((data) => !data.data?.attributes.refunded),
      Effect.catchAll(() => Effect.succeed(false)),
    ),
  )
```

**Comment by IMax153** [comment]
@cschroeter - this error occurs when you have duplicate versions of `effect` in your program, usually as a result of out-of-sync dependencies. Strange that it only occurs on Vercel and not locally as well.

Can you run the equivalent of `pnpm why effect` with whatever package manager you have and see if you can see multiple versions of effect?

**Comment by cschroeter** [comment]
@IMax153 

Thanks for the quick response. Unfortunately, there isn't a `bun why` command available right now. However I searched through `node_modules` and couldn't find anything with `3.4.7`.

---
<img width="352" alt="image" src="https://github.com/user-attachments/assets/cdc49c9d-ce97-4a9c-989e-ef3377c7a82f">

**Comment by cschroeter** [comment]
@IMax153 

I could solve it by purging the cache and force a re-deploy

<img width="970" alt="image" src="https://github.com/user-attachments/assets/5dcc50f7-17f9-46b1-9b1c-143698198d09">

**Comment by IMax153** [comment]
@cschroeter - That sounds reasonable. Let us know if it solves your issue.
