### ISSUE TITLE
Schema.Trim result in a Parsing Error when using Schema.Class and Schema.TaggedClass with "new" and "make" constructors

### ISSUE THREAD

**Issue by steffanek** [Effect-TS/effect#3336]
### What version of Effect is running?

3.5.6

### What steps can reproduce the bug?

When using `Schema.Class` or `Schema.TaggedClass`:

```ts
export class SomeForm extends Schema.TaggedClass<SomeForm>()("SomeForm", {
  userName: pipe(Schema.String, minLength(3), Schema.compose(Schema.Trim)),
}) {}

//the decode is successful here and so it's trimmed:
console.log(
  "%o",
  Schema.decodeEither(SomeForm)({
    _tag: "SomeForm",
    userName: " Jan Damme ",
  }),
)

//however here it result in a Error:
// console.log(
//   "%o make",
//   SomeForm.make({
//     userName: " Jan Damme ",
//   }),
// )
// console.log(
//   "%o new",
//   new SomeForm({
//     userName: " Jan Damme ",
//   }),
// )
```

### What is the expected behavior?

It should properly decode and trimmed the userName values when using both "new" and "make" constructors.

### What do you see instead?

a ParseError

### Additional information
Tested with both:
@effect/schema 0.68.26
@effect/schema 0.69.1

_No response_

**Comment by gcanti** [comment]
That's expected, here's the definition of `Trim`

```ts
export class Trim extends transform(
  String$,
  Trimmed,
  { strict: true, decode: (s) => s.trim(), encode: identity }
).annotations({ identifier: "Trim" }) {}
```

The target of the transformation is `Trimmed` and `SomeForm.make` expects a value conforming to that
