### ISSUE TITLE
Config: Expected VALUE to exist in the process context

### ISSUE THREAD

**Issue by BorisZubchenko** [Effect-TS/effect#3427]
### What version of Effect is running?

3.6.1

### What steps can reproduce the bug?

[Open the reproduction](https://stackblitz.com/edit/stackblitz-starters-7vwuxk?file=app%2Fpage.tsx)

### What is the expected behavior?

I want the value from the config to be resolved

### What do you see instead?

`(FiberFailure) Error: (Missing data at NEXT_PUBLIC_CONFIG_VALUE: "Expected NEXT_PUBLIC_CONFIG_VALUE to exist in the process context")`

### Additional information

Initially, I received this error implementing a Convex Function. However, `process.env` also worked fine there. So I decided to create a reproduction. Unfortunately, it doesn't work too.

**Comment by KhraksMamtsov** [comment]
You can't access environment variables in the browser dynamically
They are inlined by the engine only when accessed directly
Literally like this `process.env.NEXT_PUBLIC_MY_VAR` 
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

However, you can create a `ConfigProvider` from the inlined values and provide it
```ts
'use client';

import { useEffect } from 'react';
import { Config, Effect, ConfigProvider } from 'effect';

const NextConfigProvider = ConfigProvider.fromMap(
  new Map([
    [
      //
      'NEXT_PUBLIC_CONFIG_VALUE',
      process.env.NEXT_PUBLIC_CONFIG_VALUE!,
    ],
  ])
);

export default function Home() {
  useEffect(() => {
    console.log('process.env', process.env.NEXT_PUBLIC_CONFIG_VALUE);
    const result = Effect.runSync(
      Config.string('NEXT_PUBLIC_CONFIG_VALUE').pipe(
        Effect.withConfigProvider(NextConfigProvider)
      )
    );
    console.log('effect', result);
  }, []);

  return <div>{process.env.NEXT_PUBLIC_CONFIG_VALUE}</div>;
}
```

**Comment by BorisZubchenko** [comment]
You're right. Forgot about that. Sorry.

The only thing is that it doesn't work in [Convex Runtime](https://docs.convex.dev/functions/runtimes#default-convex-runtime), which is not a browser. The worst part about that is that it would be hard to create an easily accessible reproduction.

**Comment by mikearnaldi** [comment]
For environments that require static access you'll need a custom provider and to list explicitely the env variables, nothing we can do. Would be good to open this issue in convex to see if there is a prefix like next that would automatically inline variables
