### ISSUE TITLE
Passing a default value to `Prompt.text` from @effect/cli has no effect.

### ISSUE THREAD

**Issue by cdierkens** [Effect-TS/effect#3465]
### What version of Effect is running?

"@effect/cli@0.41.0","@effect/platform@0.62.0","@effect/platform-node@0.57.0","effect@3.6.4"

### What steps can reproduce the bug?

https://stackblitz.com/edit/stackblitz-starters-m1qrud?file=index.ts

### What is the expected behavior?

The default value passed in as the `TextOptions` argument on a `Prompt.text` call will be respected.

### What do you see instead?

There is no default value set.

**Comment by IMax153** [comment]
Thanks for the report @cdierkens - I'll take a look at this early next week 👍

**Comment by cdierkens** [comment]
@IMax153 Thanks for the quick response.

I attempted a PR myself, but could not get the tests to accept the `Enter` key. I'm very beginner with `Effect` so I'm absolutely sure there are better ways to test.

**Comment by IMax153** [comment]
@cdierkens - we always welcome contributions! 

If you would like some help getting your PR across the finish line I would be happy to work with you. If interested just open a draft PR 👍

**Comment by cdierkens** [comment]
@IMax153 Would love some help!

Here's the PR

https://github.com/Effect-TS/effect/issues/3465
