### ISSUE TITLE
Dual overload signature problem

### ISSUE THREAD

**Issue by thomasvargiu** [Effect-TS/effect#3472]
### What version of Effect is running?

effect:3.6.4

### What steps can reproduce the bug?

```ts
import type { DateTime } from 'effect/DateTime'
import { unsafeNow, distance } from 'effect/DateTime'
import * as E from 'effect/Either'

// same DateTime.distance() overload signature
declare const distanceA: {
    (that: DateTime): (self: DateTime) => number
    (self: DateTime, that: DateTime): number
}

// inverted overload signature
declare const distanceB: {
    (self: DateTime, that: DateTime): number
    (that: DateTime): (self: DateTime) => number
}

const original = E.right(unsafeNow()).pipe(
    E.map(distance) // error
)

const a = E.right(unsafeNow()).pipe(
    E.map(distanceA) // error
)

const b = E.right(unsafeNow()).pipe(
    E.map(distanceB) // NO error
)

```

### What is the expected behavior?

I expect to use functions in a functional way.

### What do you see instead?

I'm unable to code in a simple functional way composing functions

### Additional information

Inverting the overload signature should work (for me).
I'm using typescript: 5.5.4

**Comment by mikearnaldi** [comment]
This is expected, Effect doesn't generally support tacit function calling, you'll need to make the call explicit: `map((x) => distance(x))` this is due to TS limitations in checking overloads

**Comment by thomasvargiu** [comment]
@mikearnaldi do you think that inverting overload signatures in order to support it could cause different problems?
Is it something already discussed?

**Comment by thomasvargiu** [comment]
@mikearnaldi for what I know and what I read, Typescript use the first signature matched. Moving the complete function signature first, it should enable my use case.

So, it's not a bug, but if I'm not wrong it will be a huge improvement since I'm coming from @gcanti  [`fp-ts`](https://github.com/gcanti/fp-ts)

**Comment by mikearnaldi** [comment]
It has been discussed already, order of parameters is optimised for auto-completions and for tacit usage in places that expect `(a, b) => x`.

Coming from fp-ts you'll need to adapt to the technical choices of effect, fp-ts promoted tacit usage while effect forbids it due to safety concerns + improved stack tracing
