### ISSUE TITLE
sql-kysely: cannot use transaction 

### ISSUE THREAD

**Issue by fredericrous** [Effect-TS/effect#3520]
### What version of Effect is running?

@effect/sql-kysely@0.5.0

### What steps can reproduce the bug?

We cannot use transaction when instantiating @effect/sql-kysely ourselves (in order to provide a custom dialect)

- go to packages/sql-kysely/test/Kysely.test.ts
- try to add a test with a transaction

```ts
  it.effect("transaction", () =>
    Effect.gen(function* (_) {
      const db = yield* KyselyDB
      db.withTransaction // withTransaction is not available
```

- notice `withTransaction` is not available as a property of `db`

### What is the expected behavior?

withTransaction should be available. db signature should be the patched version EffectKysely<DB>

### What do you see instead?

transaction. db signature is Kysely<DB>

### Additional information

workaround, under `src/internal/kysely.ts`

edit `makeWithExecute` and cast `db` variable

```ts
export const makeWithExecute = <DB>(config: KyselyConfig) => {
  const db = new Kysely<DB>(config) as unknown as EffectKysely<DB>
 ...
}
```

**Comment by mikearnaldi** [comment]
The normal withTransaction from the sql package can be used as kysley uses the connection from sql

**Comment by fredericrous** [comment]
hey @mikearnaldi . I did not understand your answer, how would you do this? withTransaction exists but is not suggested because the wrong type is being returned

**Comment by fredericrous** [comment]
I remember why I was not using `withTransaction` from the sql package... it's because I was not using effect/sql-kysely....because this package forces you to use a dialect and I cannot chose the dialect I want :'(
