### ISSUE TITLE
sql-kysely: @effect/sql dependency missing

### ISSUE THREAD

**Issue by fredericrous** [Effect-TS/effect#3521]
### What version of Effect is running?

@effect/sql-kysely@0.5.0

### What steps can reproduce the bug?

I used the following code to notice the bug

```ts
import * as SqlKysely from "@effect/sql-kysely/Kysely"
import Database from "better-sqlite3"
import { Context, Layer } from "effect"
import { type Generated, SqliteDialect } from "kysely"

export interface EventJournal {
  id: Generated<number>
  execution_id: string
  sequence: number
  event_json: string
}

export interface Database {
  event_journal: EventJournal
}

export class SqliteDB extends Context.Tag("SqliteDB")<SqliteDB, SqlKysely.EffectKysely<Database>>() {}

const dialect = new SqliteDialect({
  database: new Database("database.sqlite3")
})
export const KyselyLive = Layer.sync(SqliteDB, () =>
  SqlKysely.make<Database>({
    dialect: dialect as any
  }) as unknown as SqlKysely.EffectKysely<Database>)
```

### What is the expected behavior?

I should not need @effect/sql because the code uses `makeWithExecute` and not `makeWithSql` in file src/internal/kysely.ts

### What do you see instead?

@effect/sql because `makeWithSql` depends on `import * as Client from "@effect/sql/SqlClient"`

### Additional information

workaround is to install `@effect/sql`, fix could be to have makeWithExecute and makeWithSql in there own files?Adding `@effect/sql` to peerDependencies in package.json seems like a good idea

**Comment by mikearnaldi** [comment]
`@effect/sql` is listed as a peer dependency, standard in JS for packages that require to be installed at the root project. See https://github.com/Effect-TS/effect/blob/main/packages/sql-kysely/package.json#L60 . depending on the npm client you're using it can be auto-installed or needs to be manually installed, in any case this isn't a bug.

**Comment by fredericrous** [comment]
indeed, I missed this in the peer dependencies. I did the install with pnpm and it did not install the peer dependency like npm would have.

anyway, I think there is something here, I should not have to install `@effect/sql` when I do not use it. the peer dependency should be optional

```
"peerDependenciesMeta": {
  "@effect/sql": {
    "optional": true
  }
}
```

**Comment by mikearnaldi** [comment]
No it should not, given that the kysley integration uses it.

**Comment by fredericrous** [comment]
if integration means mysql, sqlite and co, yes they use it, but if you have a custom dialect, for sqlite wasm for example, you won't use `@effect/sql` at this exact place I noticed in `src/internal/kysely.ts` ..... however, indeed I'm supposed to use `@effect/sql` anyway on top of `@effect/sql-kysely`, to get schema encoding/decoding.

I'm still learning and there's not always complete documentation depending on the modules so I'm learning slowly by trial and error :)
