### ISSUE TITLE
sql-kysely: Error not explicit

### ISSUE THREAD

**Issue by fredericrous** [Effect-TS/effect#3522]
### What version of Effect is running?

@effect/sql-kysely@0.5.0

### What steps can reproduce the bug?

- use a setup like https://github.com/Effect-TS/effect/issues/3521
- log error with @effect/Logger like so: Logger.withMinimumLogLevel(LogLevel.All),
- then insert into a non existing table

### What is the expected behavior?

I should get an error that I can understand

### What do you see instead?

I see only `SqlError`. here is the complete error

```log
timestamp=2024-08-30T23:19:16.638Z level=DEBUG fiber=#2 message="Fiber terminated with an unhandled error" cause="SqlError
    at cause (/my-project/node_modules/.pnpm/@effect+sql-kysely@0.5.0_@effect+sql@0.10.0_@effect+experimental@0.24.0_@effect+platform-node_boill4fvc32tejkn3w5hoksn3a/node_modules/@effect/sql-kysely/src/internal/patch.ts:70:23)
    at e (/my-project/node_modules/.pnpm/effect@3.1.1/node_modules/effect/src/internal/core-effect.ts:1670:23)
    at kysely.execute"
```

**Comment by mikearnaldi** [comment]
Message rendering could be improved, cc @tim-smart but this isn't a bug.

**Comment by tim-smart** [comment]
Have you got some example code? So I can see how the error is being logged.

**Comment by fredericrous** [comment]
I can't reproduce the issue anymore. I might have been on an old version of one of the packages. closing the issue
