### ISSUE TITLE
Reference documentation?

### ISSUE THREAD

**Issue by tmcw** [Effect-TS/effect#3562]
### What is the type of issue?

Documentation is missing

### What is the issue?

The guide-style documentation is great, but I find myself missing reference/API style documentation, like what TypeDoc would output - I'd like to know things like "what are all of the methods on the Effect object".

### Where did you find it?

This is for something I couldn't find.

**Comment by IMax153** [comment]
@tmcw - at the moment it's hosted separately from the official docs at https://effect-ts.github.io/effect. There are links to the API reference on the Effect website from the left sidebar of the docs under "API Reference".

At some point in the future, the API reference docs will also be hosted on the Effect website.
