### ISSUE TITLE
HttpClient: Allow json body in GET requests

### ISSUE THREAD

**Issue by relsunkaev** [Effect-TS/effect#3598]
### What version of Effect is running?

3.7.2

### What steps can reproduce the bug?

Try sending a GET request with a json body

### What is the expected behavior?

Attaches the JSON body

### What do you see instead?

Body is omitted in the request

### Additional information

I understand fetch throws an error in this case but silently dropping the body is unexpected.

The offending code is [here](https://github.com/Effect-TS/effect/blob/8632f7dd8c864fff3260de12cac21d34d2c252b7/packages/platform/src/internal/httpClient.ts#L223).

**Comment by Dhiraj5789** [comment]
Hi @relsunkaev, can you assign this bug to me? I would love to contribute on this

**Comment by tim-smart** [comment]
This has been fixed now :)
