### ISSUE TITLE
Schema: Highlight feature differences between Class definition and Struct definition

### ISSUE THREAD

**Issue by florianbepunkt** [Effect-TS/effect#3681]
### What is the type of issue?

Something else

### What is the issue?

This is something between documentation, maybe bug and a feature request.

I have some rather big schemas in an ecommerce domain I am migrating to Effect. From the docs I understood that defining a schema as a class is a syntactic alternativ to defining it as a struct:

> When you define a class using Schema.Class, it not only creates a new class but also treats this class as a schema. This means the class can be utilized wherever a schema is expected.

 But there are some incompatibilities. Not sure if they constitute a bug (probably rather by design). Here is an example that works when using structs, but fails with a class definition.

```ts
import { Schema as S } from "@effect/schema";

// Working when using structs
const AggregateState = S.Struct({ _id: S.NonEmptyString });
const DraftInvoice = S.Struct({ createdAt: S.DateFromString, status: S.Literal("draft") });
const IssuedInvoice = S.Struct({ ...DraftInvoice.fields, status: S.Literal("issued"), number: S.String });
const Invoice = S.Union(DraftInvoice, IssuedInvoice);
const InvoiceAggregateState = AggregateState.pipe(S.extend(Invoice));

const parse = S.decodeUnknownSync(InvoiceAggregateState);
const result = parse({ _id: "test", name: "foo", status: "draft" });
console.log(result); // <-- Working, returns a parse error

// Not working when using classes
class AggregateStateC extends S.Class<AggregateStateC>("AggregateStateC")({ _id: S.NonEmptyString }) {}

class DraftInvoiceC extends S.Class<DraftInvoiceC>("DraftInvoiceC")({
  createdAt: S.DateFromString,
  status: S.Literal("draft"),
}) {}

class IssuedInvoiceC extends S.Class<IssuedInvoiceC>("IssuedInvoiceC")({
  ...DraftInvoice.fields,
  number: S.String,
  status: S.Literal("issued"),
}) {}

const InvoiceC = S.Union(DraftInvoiceC, IssuedInvoiceC);
const InvoiceAggregateStateC = AggregateStateC.pipe(S.extend(InvoiceC));

const parseC = S.decodeUnknownSync(InvoiceAggregateStateC);
const resultC = parseC({ name: "foo", status: "draft" });
console.log(resultC); // <-- Not working, returns Error: Unsupported schema or overlapping types

```

If this is not a bug, it would be a good idea to describe the differences / limitations of the class api. What also tripped me is that you can do  picks and omits on a struct `S.Struct({foo: S.Boolean}).pick("foo)` but not on a class.

For our use case we need to compose schemas like in the example above, but they are more complex and larger in length. What is challenging: I would like the intellisense to show simply Invoice or the interface / class name. But since I can't use the class definition (see above), with the struct I always see the whole object. This makes the type signatures of our effect code unreadable and basically useless.

**Comment by gcanti** [comment]
The following code doesn't work

```ts
const InvoiceAggregateStateC = AggregateStateC.pipe(S.extend(InvoiceC));
```

because `S.Class` defines a schema as a transformation (*), and `S.extend` does not support transformations.


(*) for example this

```ts
class AggregateStateC extends S.Class<AggregateStateC>("AggregateStateC")({ _id: S.NonEmptyString }) {}
```

implicitly defines a transformation from a value `{ _id: S.NonEmptyString }` to an instace of `AggregateStateC`

**Comment by florianbepunkt** [comment]
Understood. But the same approach works when using structs. And on a type level, the operation is allowed with the class API – I only got an error during runtime. So class API / non-class API aren't fully cross-compatible? 

Using the struct api I loose the simplified type signature showing up in my IDE. Bummer.

**Comment by gcanti** [comment]
> So class API / non-class API aren't fully cross-compatible?

Correct, they are not interchangeable. The documentation states that you can use a class as a schema, but it does not imply that a class is equivalent to a struct. While `Schema.Class` always defines a transformation, a `Struct` does not.

> Using the struct api I loose the simplified type signature showing up in my IDE. Bummer.

Keep in mind that when using `S.extend`, you already lose the nice type signatures. Instead, you can just extend the encoded parts of the classes:

```diff
-const InvoiceAggregateStateC = AggregateStateC.pipe(S.extend(InvoiceC))
+const InvoiceAggregateStateC = S.encodedSchema(AggregateStateC).pipe(S.extend(S.encodedSchema(InvoiceC)))
```
