### ISSUE TITLE
Http: Automatic request idempotency 

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/effect#3708]
### What is the problem this feature would solve?

It would be nice to have a set of client and server middleware that automatically handle generating and adding an idempotency token to all requests from the client and handling caching and resending of responses for a repeated request with the same token on the server.

### What is the feature you are proposing to solve the problem?

A set of client and server middleware that transparently handle generating tokens, adding tokens to client requests, caching responses for a given token, and reserving the cached value when a request with a repeated token is received.

**Comment by mikearnaldi** [comment]
I don't see how idempotency can be automatic, idempotency keys are domain specific

**Comment by mikearnaldi** [comment]
also it would need a serializeable request/response and a transactional storage which is propagated to user-land, feels out of scope imho
