### ISSUE TITLE
`Stream.fromReadableStream` leaves the `ReadableStream` in a locked state.

### ISSUE THREAD

**Issue by skoshx** [Effect-TS/effect#3774]
### What version of Effect is running?

`latest`

### What steps can reproduce the bug?

Reproduction in this Effect Playground

https://effect.website/play#bc147f507d11

### What is the expected behavior?

Expected, that lock on the stream is released. Source code calls `.cancel` instead of `.releaseLock`.

### What do you see instead?

Stream stays locked and is thus unusable a second time.

**Comment by tim-smart** [comment]
This is working as intended (https://effect.website/play#9b44cc8f15d0), but we can add an option to call .releaseLock instead in the case you want to share a stream instead of finalizing it.

**Comment by skoshx** [comment]
Hey, yeah It seems so... Interestingly when I shared the Playground it was throwing errors... Not sure if it was just some bad state or what :D But yeah, that sounds good!
