### ISSUE TITLE
Interop: Transform between HttpClientRequest and node's Request

### ISSUE THREAD

**Issue by florianbepunkt** [Effect-TS/effect#3788]
### What is the problem this feature would solve?

We have multiple occasions where we need to sign http requests (for example with AWS Signature v4). Signing is non-trivial and often external systems offer sdks for it. These third-party libraries use the native Request object from NodeJS. 

Currently we cannot use them since there is no way to map between a HttpClientRequest and a "native" Node request. For the streams module such methods exist.

### What is the feature you are proposing to solve the problem?

```typescript
import { HttpClient, HttpClientRequest } from "@effect/platform";
import { Effect } from "effect";

declare function sign(a: Request): Request; // comes from third party, returns a signed request (with signature attached to header/body, etc).

declare function proposedToNodeRequest(a: HttpClientRequest.HttpClientRequest): Request;
declare function proposedFromNodeRequest(a: Request): HttpClientRequest.HttpClientRequest;

const program = Effect.gen(function* () {
  const client = (yield* HttpClient.HttpClient).pipe(
    HttpClient.mapRequest((req) => {
      const nativeNodeRequest = proposedToNodeRequest(req);
      const signed = sign(nativeNodeRequest);
      return proposedFromNodeRequest(signed);
    }),
  );
});

```

**Comment by tim-smart** [comment]
You can inject a custom fetch function, if you want to inject something that works with the web Request api: https://github.com/Effect-TS/effect/tree/main/packages/platform#injecting-fetch

**Comment by florianbepunkt** [comment]
@tim-smart Thank you. It works, but feels a bit off api-wise to inject a fetch in order to access/map the native request object. Maybe exposing constructors/destructors for the native request might be more idiomatic. Closing this.

**Comment by tim-smart** [comment]
> @tim-smart Thank you. It works, but feels a bit off api-wise to inject a fetch in order to access/map the native request object. Maybe exposing constructors/destructors for the native request might be more idiomatic. Closing this.

The HttpClient module targets several different platforms, so it isn't always backed by a `Request` object.
