### ISSUE TITLE
Schema const enums

### ISSUE THREAD

**Issue by decoursin** [Effect-TS/effect#3847]
### What is the problem this feature would solve?

Zod supports these [fixed set enums](https://github.com/colinhacks/zod?tab=readme-ov-file#zod-enums) which are like arrays declared with the `const` keyword. I was hoping Effect's `Schema` could also.

### What is the feature you are proposing to solve the problem?

Support for const arrays.

### What alternatives have you considered?

I have tried `Schema.Enums` which doesn't work.

**Comment by jessekelly881** [comment]
I believe you want
```ts
Schema.Literal("a", "b")
```

**Comment by decoursin** [comment]
@jessekelly881 Thanks. The `Schema.Literal(...arr)` works. Sorry for the inconvenience. I suppose an [example](https://github.com/Effect-TS/effect/blob/main/schema/comparisons.md) might be good, but IDK up to you!
