### ISSUE TITLE
`Stream.decodeText` replaces `E` (error type) and `R` (requirements type) with `unknown`

### ISSUE THREAD

**Issue by skoshx** [Effect-TS/effect#3890]
### What version of Effect is running?

"effect": "^3.10.6",

### What steps can reproduce the bug?

```typescript
const x: Stream.Stream<Uint8Array, PlatformError, never> = Stream.make()
const y = x.pipe(Stream.decodeText)
//    ^ y is `Stream.Stream<string, unknown, unknown>`
```

### What is the expected behavior?

Expected `y` to be `Stream.Stream<string, PlatformError, never>`

### What do you see instead?

`y` is `Stream.Stream<string, unknown, unknown>`

**Comment by tim-smart** [comment]
Stream.decodeText takes an optional argument, so it should be `Stream.decodeText()` there.

**Comment by skoshx** [comment]
Whoops, totally missed that! Thanks, closing.
