### ISSUE TITLE
change from `HttpApiGroup.Group` to `HttpApiGroup.ApiGroup` isn't reflected in docs / `README.md`

### ISSUE THREAD

**Issue by skoshx** [Effect-TS/effect#3914]
### What is the issue?

change from `HttpApiGroup.Group` to `HttpApiGroup.ApiGroup` isn't reflected in docs / `README.md`

### Where did you find it?

My code using `HttpApiGroup.Group` no longer works with newest Effect version.

**Comment by gcanti** [comment]
Fixed in https://github.com/Effect-TS/effect/pull/3916
