### ISSUE TITLE
allow Override annotation to be a function in http platform

### ISSUE THREAD

**Issue by ryskajakub** [Effect-TS/effect#3952]
### What is the problem this feature would solve?

when I annotate the http platform api with override, that can be then used when rendering the openapi,
i can only add override, which will merge the two objects.
```
export const api = HttpApi.empty
  .add(restApi)
  .annotate(Override, { components: { schemas: "def" }})
```
=> all schemas are replaced with "def" 

### What is the feature you are proposing to solve the problem?

What I'd like to instead have is be able to supply a function that would take the generated specificiation and would return a modificated version of that. In this way, I could for example add an element to the schemas:
```
const MySchema = ...
export const api = HttpApi.empty
  .add(restApi)
  .annotate(Override, (orig) => ({ ...orig, components: { ...orig.components, 
      schemas: { ...orig.components.schemas, MySchema } } } ))
```

### What alternatives have you considered?

alternative would be to copy the `HttpApiSwagger.layer` function and apply some modification after the `OpenApi.fromApi(api)` call

**Comment by ryskajakub** [comment]
looks good, thanks! this also could be used on group and endpoint level the same way Override is used

**Comment by tim-smart** [comment]
It can now be used in all places Override can be used :)
