### ISSUE TITLE
Recursive schema definition with non primitive data

### ISSUE THREAD

**Issue by Elmaranin** [Effect-TS/effect#3964]
### What version of Effect is running?

effect@3.10.15

### What steps can reproduce the bug?

Take default example from [Helpful Pattern to Simplify Schema Definition](https://effect.website/docs/schema/advanced-usage/#a-helpful-pattern-to-simplify-schema-definition)
Change `name` field type to `Schema.Date` like this
```ts
const fields = {
  name: Schema.Date
}
```

### What is the expected behavior?

TS shows no errors

### What do you see instead?

Type 'Struct<{ subcategories: Array$<suspend<Category, Category, never>>; name: typeof Date$; }>' is not assignable to type 'Schema<Category, Category, never>'.
  The types of 'Encoded.name' are incompatible between these types.
    Type 'string' is not assignable to type 'Date'.ts(2322)

### Additional information

That's because `Date` uses `String` schema and transforms it. What should I do to keep type safe?
Similar problems occur to me if I use `transform` operation in one of the fields.

**Comment by nspaeth** [comment]
If [Recursive Types with Different Encoded and Type](https://effect.website/docs/schema/advanced-usage/#recursive-types-with-different-encoded-and-type)  does not address the issue, can you share a link to a playground that demonstrates the issue more clearly?

**Comment by Elmaranin** [comment]
Yes, of course: https://effect.website/play/#bb624b76d12e

**Comment by Elmaranin** [comment]
Thanks, that explain everything!
