### ISSUE TITLE
Platform: Add possibility to rename security identifier in the OpenApi

### ISSUE THREAD

**Issue by janydoe** [Effect-TS/effect#3965]
### What is the problem this feature would solve?

now the open api displays the identifier that we specify as the key in security. and there is no way to rename it using the `HttpApiSecurity.annotate` or `HttpApiSecurity.annotateContext`.

### What is the feature you are proposing to solve the problem?

Add the ability to change the identifier using the OpenApi.Identifier

**Comment by KhraksMamtsov** [comment]
Could you give me an example?  Why is an identifier of the same name not enough?
