### ISSUE TITLE
`Effect.Service` with `accessors` break if generics are used in the services' functions

### ISSUE THREAD

**Issue by skoshx** [Effect-TS/effect#3988]
### What version of Effect is running?

"effect": "3.10.16",

### What steps can reproduce the bug?

Playground here: https://effect.website/play#1e0caa2543d2

```typescript
export class GenericsService extends Effect.Service<GenericsService>()("GenericsService", {
  effect: Effect.gen(function*() {
    const query = <T>(element: T) => Effect.succeed(element)
    return { query }
  }),
  accessors: true,
}) {}

// @ts-expect-error: As you can see, `query` isn't available here:
const x = GenericsService.query

export class NoGenericsService extends Effect.Service<NoGenericsService>()("NoGenericsService", {
  effect: Effect.gen(function*() {
    const query = (element: string) => Effect.succeed(element)
    return { query }
  }),
  accessors: true,
}) {}

// As you can see, `query` IS AVAILABLE here:
const y = NoGenericsService.query

```

### What is the expected behavior?

Expected to be able to access `GenericsService.query` normally, since `accessors` is set to true.

### What do you see instead?

Can't access it. Have to `yield* GenericsService` and then access `.query`

**Comment by mikearnaldi** [comment]
It's unfortunately a limitation of TS when type transformations are applied generics are replaced with `unknown` so we exclude the generic functions from the auto-proxy.

You can get the `query` function by hand like (https://effect.website/play#289488ec4603):

```ts
import { Effect } from "effect"

export class GenericsService extends Effect.Service<GenericsService>()("GenericsService", {
  effect: Effect.gen(function*() {
    const query = <T>(element: T) => Effect.succeed(element)
    return { query }
  }),
  accessors: true,
}) {
  static query = Effect.serviceFunctionEffect(this, _ => _.query)
}

const x = GenericsService.query
```

**Comment by skoshx** [comment]
@mikearnaldi Oh okay totally understandable! Thanks for the quick reply and the workaround, works perfectly for my usecase!🙌

Closing :)
