### ISSUE TITLE
Empty struct equivalence fails with empty objects

### ISSUE THREAD

**Issue by kalda341** [Effect-TS/effect#4003]
### What version of Effect is running?

3.10.17

### What steps can reproduce the bug?

```
import { Schema } from "effect"

const struct = Schema.Struct({});
console.log(Schema.equivalence(struct)({}, {}))
```

### What is the expected behavior?

Empty objects should be considered equivalent.

### What do you see instead?

Empty objects are not considered equivalent.

**Comment by gcanti** [comment]
`Schema.Struct({})` represents the TypeScript `{}` type, which behaves similarly to `any`. 

Therefore `Schema.equivalence(struct)` compares the arguments using reference equality (`===`):

```ts
import { Schema } from "effect"

const struct = Schema.Struct({})

const input = {}

console.log(Schema.equivalence(struct)(input, input))
// Output: true
```

Given that the values can be anything, reference equality appears to be the most appropriate form of equivalence to use in this case (as well as with `any`, `unknown`, and `object`).

**Comment by kalda341** [comment]
Thanks for the clarification. I think that's a reasonable assertion, however, I think it could lead to unexpected outcomes:

```ts
import { Schema } from "effect"

const object1 = { a: 'a', b: 'b' };
const object2 = { a: 'a', b: 'b' };

const schemaAB = Schema.Struct({
  a: Schema.String,
  b: Schema.String,
});

// Equivalent
console.log(Schema.equivalence(schemaAB)(object1, object2));

// Equivalent
console.log(Schema.equivalence(schemaAB.omit('a'))(object1, object2));

// Not equivalent, this behaviour is surprising
console.log(Schema.equivalence(schemaAB.omit('a', 'b'))(object1, object2));
```

I would have thought that by omitting additional properties you could only make an equality check less strict, not stricter. I am however in agreement about the existing behaviour of Any, Unknown and Object.

Thank you so much for all your work in schema, I could not live without it.
