### ISSUE TITLE
[rpc] Unable to use next.js cache

### ISSUE THREAD

**Issue by MrOxMasTer** [Effect-TS/effect#4037]
### What version of Effect is running?

3.10.19

### What steps can reproduce the bug?

```ts
export class UserByEmail extends S.TaggedRequest<UserByEmail>()('UserByEmail', {
  failure: S.Union(
    S.instanceOf(UnknownDatabaseError),
    S.instanceOf(UserNotFoundError),
  ),
  success: selectUserSchema,
  payload: { email: userEmailSchema },
}) {}

export const userRouter = RpcRouter.make(
  Rpc.effect(UserByEmail, async ({ email }) => {
    'use cache';

    const res = Effect.gen(function* (_) {
      const db = yield* DBClient;

      const user = yield* _(
        Effect.tryPromise({
          try: () =>
            db.query.users.findFirst({
              where: (users, { eq }) => eq(users.email, email),
            }),
          catch: (error) =>
            new UnknownDatabaseError({
              message: `${error}`,
            }),
        }),
        Effect.filterOrElse(
          (user) => !!user,
          () => new UserNotFoundError(),
        ),
      );

      return yield* Effect.succeed(user);
    }).pipe(Effect.provideService(DBClient, db));

    return res;
  }),
);

export type UserRouter = typeof userRouter;

const handler = RpcRouter.toHandler(userRouter);
const resolver = RpcResolver.make(handler)<typeof userRouter>();
export const client = RpcResolver.toClient(resolver);
```

1. To try to cache this function and figure out what:
- Need an asynchronous function (No rpc documentation, so I'm using `Rpc.effect` because I don't know what else I can do)
- Understand that the returned result is Effect or Exit, which cannot be another value (otherwise ts error), and such a value cannot be cached because it is not serializable, and you cannot return an encoded value because you need an effect
![image](https://github.com/user-attachments/assets/b68694dc-f5e7-4a3c-b1a5-236b15f9448d)
![image](https://github.com/user-attachments/assets/f09fb9d1-c17c-4a6f-9a64-4cda39292d85)
![image](https://github.com/user-attachments/assets/aa35c45d-b248-421a-b9d6-89cc55ec5798)

### What is the expected behavior?

without error

### What do you see instead?

![image](https://github.com/user-attachments/assets/22edbfd3-62fe-4839-a1e8-ceb9567ad0fe)

**Comment by datner** [comment]
I don't know enough about the internal mechanism involved, but I can tell you that the `"use cache"` is in an invalid location. Nextjs does not understand this kind of execution strategy, it would expect something like this
```ts
const foo = async () => {
 "use cache";
  const res = await runPromise(doFoo)

  return res
}
```

rather than something like this:
```ts
const foo = async () => {
  const doFoo = async () => {
   "use cache";
    // ...
  }

  const res = await doFoo()

  return res
}
```

There are too many variables involved, I cannot narrow down a useful answer I'm afraid

**Comment by MrOxMasTer** [comment]
> I don't know enough about the internal mechanism involved, but I can tell you that the `"use cache"` is in an invalid location. Nextjs does not understand this kind of execution strategy, it would expect something like this

Yes, indeed, I can't cache because the function used inside `Rpc.effect` is not asynchronous.
Moreover, even if it is asynchronous, I can't cache anyway because it returns `effect` which is not a serializable value. If I make it `Exit`, then `exit` can return but it is also not a serializable value. When I try to code `Exit`, I'm already getting complained by `ts` that the return type is not appropriate

**Comment by mikearnaldi** [comment]
RPC is not really meant to be used with next.js "use cache", that's a specific directive to apply to next.js functions

**Comment by MrOxMasTer** [comment]
> Reference in new

Well, yes, I don't argue that `@effect/rpc` was not specifically intended for `next.js`, but it's strange that it doesn't work. Code comes in different forms as do libraries/frameworks too. It's weird to hope that `package.json` will only have effect and nothing else.

**Comment by mikearnaldi** [comment]
> > Reference in new
> 
> Well, yes, I don't argue that `@effect/rpc` was not specifically intended for `next.js`, but it's strange that it doesn't work. Code comes in different forms as do libraries/frameworks too. It's weird to hope that `package.json` will only have effect and nothing else.

that is not the hope, Effect is written in plain JS so we don't make any assumption. The issue here is that next.js uses custom directives that are outside of the JS specification so the behaviour is specific to the patterns they want to support. In this case the pattern they want to support is caching single functions.

**Comment by mikearnaldi** [comment]
> > Reference in new
> 
> Well, yes, I don't argue that `@effect/rpc` was not specifically intended for `next.js`, but it's strange that it doesn't work. Code comes in different forms as do libraries/frameworks too. It's weird to hope that `package.json` will only have effect and nothing else.

Also we've kept answering but your way of saying things is really demotivating and entitled, unless you change and be positive in engaging we're simply going to stop providing help.

**Comment by MrOxMasTer** [comment]
> Also we've kept answering but your way of saying things is really demotivating and entitled, unless you change and be positive in engaging we're simply going to stop providing help.

I do not put any negativity into my posts. If I did, I wouldn't care and I just wouldn't use `effect`, and so, you see, I leave feedback and try to help develop it. Because let me remind you, the lib is really hard to understand and present itself to other people.

I don't want to demotivate you because I like the library and there are some really cool solutions and combinations, like the built-in ‘pattern matching’, the pipe function which I like, the use of generator functions to make it look like normal code and that's great, the built-in validation.

For you as a developer of this library, or maybe not a developer but a long time user of this library, you understand everything in `effect`. But I think most people just don't like the way the library is made and its design. This is proved by the stars on github, because it is not clear how a library that has 1,5 million downloads on npm has 10k, while trpc of the same library has 2 times less downloads and 2 times more stars.

Rather demotivating is your attitude towards that same library and its use, because all the response I get is ‘well that's the way it's done, that's the way we came up with it, we're not going to change anything’. 

‘Your library doesn't mix with major frameworks?’ - ‘well, not our problem. Next.js doesn't fit the js specification’. Although as far as I know, user directives will be as a separate feature soon, if it's not already contributed and it will be part of the js spec.

‘Why write boilerplate code and repeat the same expected errors?’ - ‘Well, if you don't care so much, use S.Any.’

‘Your library is inconvenient to use’ - “Well, that's the way we designed it”.

Half of the objects in rpc/platform I don't understand what they do and find examples from github -> test file, their api is on another site. Yes, you can say about it that they don't have a major version there, but I think a lot of libraries don't have a major version, and popular ones at that, such as `drizzle orm`, but I haven't had so many issues or inconsistencies there.

Certainly, my words are not a panacea, and some points - this is a taste, but still, I think that something should be changed, and it looks like I'm not the only one who thinks so.

**Comment by mikearnaldi** [comment]
Given that even this interaction turned out to be negative I have no choice but to prevent you from interacting in the repo.

**Comment by mikearnaldi** [comment]
> > Also we've kept answering but your way of saying things is really demotivating and entitled, unless you change and be positive in engaging we're simply going to stop providing help.
> 
> I do not put any negativity into my posts. If I did, I wouldn't care and I just wouldn't use `effect`, and so, you see, I leave feedback and try to help develop it. Because let me remind you, the lib is really hard to understand and present itself to other people.
> 
> I don't want to demotivate you because I like the library and there are some really cool solutions and combinations, like the built-in ‘pattern matching’, the pipe function which I like, the use of generator functions to make it look like normal code and that's great, the built-in validation.
> 
> For you as a developer of this library, or maybe not a developer but a long time user of this library, you understand everything in `effect`. But I think most people just don't like the way the library is made and its design. This is proved by the stars on github, because it is not clear how a library that has 1,5 million downloads on npm has 10k, while trpc of the same library has 2 times less downloads and 2 times more stars.
> 
> Rather demotivating is your attitude towards that same library and its use, because all the response I get is ‘well that's the way it's done, that's the way we came up with it, we're not going to change anything’.
> 
> ‘Your library doesn't mix with major frameworks?’ - ‘well, not our problem. Next.js doesn't fit the js specification’. Although as far as I know, user directives will be as a separate feature soon, if it's not already contributed and it will be part of the js spec.
> 
> ‘Why write boilerplate code and repeat the same expected errors?’ - ‘Well, if you don't care so much, use S.Any.’
> 
> ‘Your library is inconvenient to use’ - “Well, that's the way we designed it”.
> 
> Half of the objects in rpc/platform I don't understand what they do and find examples from github -> test file, their api is on another site. Yes, you can say about it that they don't have a major version there, but I think a lot of libraries don't have a major version, and popular ones at that, such as `drizzle orm`, but I haven't had so many issues or inconsistencies there.
> 
> Certainly, my words are not a panacea, and some points - this is a taste, but still, I think that something should be changed, and it looks like I'm not the only one who thinks so.

No other choice but to block such user, no point arguing when the OG acts in bad faith.
