### ISSUE TITLE
Dynamic error acceptance in Exit scheme

### ISSUE THREAD

**Issue by MrOxMasTer** [Effect-TS/effect#4038]
### What is the problem this feature would solve?

Manual detection of each error

### What is the feature you are proposing to solve the problem?

Something underneath:

// 1 Suggestion:
```ts
export const getUserByEmailExit = S.Exit({
  failure: S.DynamicError,
  success: selectUserSchema,
  defect: S.String,
});
```

// 2 Suggestion:
```ts
export const getUserByEmailExit = S.Exit((item: Exit<A,E>) => ({
  failure: S.Error(item), // Exit<A.E> -> E
  success: selectUserSchema,
  defect: S.String,
}));
```

### What alternatives have you considered?

Manual detection of each error:
```ts
export const getUserByEmailExit = S.Exit({
  failure: S.Union(
    S.instanceOf(UnknownDatabaseError),
    S.instanceOf(UserNotFoundError),
  ),
  success: selectUserSchema,
  defect: S.String,
});
```

Exit carries possible errors as it is, I don't see the point of defining them manually unless there are exceptional cases.
Otherwise, you can just say that you don't trust your own system of passing errors and combining them from one effect/Exit to the other

**Comment by mikearnaldi** [comment]
You can use `S.Any` if you don't care.

**Comment by mikearnaldi** [comment]
```ts
import { Schema } from "effect"

const MyExit = <S extends Schema.Schema.All>(success: S) =>
  Schema.Exit({
    success,
    failure: Schema.Unknown,
    defect: Schema.Unknown
  })

const MyExitString = MyExit(Schema.String)
```

There's no need for a `DynamicError` given that errors can be anything

**Comment by MrOxMasTer** [comment]
> There's no need for a `DynamicError` given that errors can be anything

Errors can be anything, but I'm talking about errors that are pre-defined and known (i.e. expected), because there can be so many of them that it turns into a template code and a very large one at that

**Comment by mikearnaldi** [comment]
> > There's no need for a `DynamicError` given that errors can be anything
> 
> Errors can be anything, but I'm talking about errors that are pre-defined and known (i.e. expected), because there can be so many of them that it turns into a template code and a very large one at that

expected errors can be of any type `Exit<A, unknown>` is a valid `Exit` so the `DynamicError` type is `unknown`. There are two cases, either you want to define all the errors (and get a union) or you don't care (and go with unknown)

**Comment by MrOxMasTer** [comment]
> expected errors can be of any type `Exit<A, unknown>` is a valid `Exit` so the `DynamicError` type is `unknown`. There are two cases, either you want to define all the errors (and get a union) or you don't care (and go with unknown)

Wouldn't there be ` - auto-suggestion` with this approach? Then I won't be able to process even what I at least know, because all that will be `unknown` and maybe `ts` will complain?

**Comment by mikearnaldi** [comment]
> > expected errors can be of any type `Exit<A, unknown>` is a valid `Exit` so the `DynamicError` type is `unknown`. There are two cases, either you want to define all the errors (and get a union) or you don't care (and go with unknown)
> 
> Wouldn't there be ` - auto-suggestion` with this approach? Then I won't be able to process even what I at least know, because all that will be `unknown` and maybe `ts` will complain?

the type `unknown | known` is by definition `unknown`, try typing `type X = unknown | string` and see what TS gives you
