### ISSUE TITLE
Schema: extend class constructor default 

### ISSUE THREAD

**Issue by florianbepunkt** [Effect-TS/effect#4054]
### What version of Effect is running?

3.11.0

### What steps can reproduce the bug?

```ts
import { Schema as S } from "effect";

class A extends S.Class<A>("A")({
  foo: S.NonEmptyString,
}) {}

class B extends A.extend<B>("B")({
  foo: S.Literal("bar").pipe(
    S.propertySignature,
    S.withConstructorDefault(() => "bar" as const)
  ),
}) {}

B.make({
  //   foo: "bar", // <-- compiler error that should not occur IMHO if foo is omitted
});

```

### What is the expected behavior?

The constructor default should make foo optional

**Comment by gcanti** [comment]
You can't duplicate a field when using `.extend`:

```ts
import { Schema as S } from "effect"

class A extends S.Class<A>("A")({
  foo: S.NonEmptyString
}) {}

class B extends A.extend<B>("B")({
  foo: S.Literal("bar").pipe(
    S.propertySignature,
    S.withConstructorDefault(() => "bar" as const)
  )
}) {}

console.log(B.make({} as any))
/*
throws:
Error: Duplicate property signature
details: Duplicate key "foo"
*/
```

**Comment by florianbepunkt** [comment]
@gcanti  Understood. Is this a design decision or a technical limitation? Seemed legit to me, as "bar" is a subset of a non empty string. Thank you for your work on fp-ts and now on effect. Migrating a code base to it, and it's 95% a real joy to work with it.

**Comment by gcanti** [comment]
It's a design decision (and also consistent with how the `Schema.extend` API works in a similar way, i.e., it doesn't allow overlapping fields). This is because, in general, allowing fields to be overwritten is not safe, as it could interfere with any getters or methods defined on the class that rely on the previous definition.

**Comment by Nvveen** [comment]
@gcanti Is there a preferred way to replace properties in schema classes?
I have the following example code that redefines a schema in situations where the API responds with a populated field given a parameter:
```ts
export class Bankaccount extends S.Class<Bankaccount>('Bankaccount')({
  id: S.String,
  bank_account_number: S.optional(S.String),
  organisation: S.optional(S.String),
}) {
  get label() {
    return `${this.id} - ${this.bank_account_number}`;
  }
}

export class Organisation extends S.Class<Organisation>('Organisation')({
  id: S.String,
  name: S.String,
}) {}

try {
  // const populated = populate(Bankaccount, { organisation: Organisation });
  class populated extends Bankaccount.pipe(
    S.omit('organisation'),
    S.extend(
      S.Struct({
        organisation: Organisation,
      }),
    ),
  ) {}

  const decoded = S.decodeUnknownSync(populated)({
    id: 'efgh',
    bank_account_number: '5678',
    organisation: {
      id: 'org2',
      name: 'Org 2',
    },
  });
  console.log('decoded', decoded, decoded.label);
} catch (err) {
  console.error(err);
}
```
But the surprising part here is that the type of `decoded` is just a plain object, and `decoded.label` returns undefined.

**Comment by gcanti** [comment]
@Nvveen I would define a base class and then extend it for the two variants, just like you would with regular class inheritance

```ts
import { Schema as S } from "effect"

class BankId extends S.Class<BankId>("BankId")({
  id: S.String,
  bank_account_number: S.optional(S.String)
}) {
  get label() {
    return `${this.id} - ${this.bank_account_number}`
  }
}

class Bankaccount extends BankId.extend<Bankaccount>("Bankaccount")({
  organisation: S.optional(S.String)
}) {}

class Organisation extends S.Class<Organisation>("Organisation")({
  id: S.String,
  name: S.String
}) {}

class populated extends BankId.extend<populated>("populated")({
  organisation: Organisation
}) {}

const decoded = S.decodeUnknownSync(populated)({
  id: "efgh",
  bank_account_number: "5678",
  organisation: {
    id: "org2",
    name: "Org 2"
  }
})
console.log("decoded", decoded, decoded.label)
/*
decoded populated {
  id: 'efgh',
  bank_account_number: '5678',
  organisation: Organisation { id: 'org2', name: 'Org 2' }
} efgh - 5678
*/
```

**Comment by Nvveen** [comment]
In our usecase we can have objects with a lot of properties that would need to be replaced, since they are foreign keys. Playing around with this and the following sort of works, but the downside is that every schema needs the same logic to spread the keys into the schema:
```ts
import { Schema as S } from "effect"

class Organisation extends S.Class<Organisation>("Organisation")({
  id: S.String,
  name: S.String
}) {}

class BankaccountBase extends S.Class<BankaccountBase>("BankaccountBase")({
  id: S.String,
  bank_account_number: S.optional(S.String)
}) {
  static readonly foreignKeys = {
    organisation: Organisation
  }

  get label() {
    return `${this.id} - ${this.bank_account_number}`
  }
}

class Bankaccount extends BankaccountBase.extend<Bankaccount>("Bankaccount")({
  ...Object.fromEntries(Object.keys(BankaccountBase.foreignKeys).map((k) => [k, S.optional(S.String)]))
}) {}


class populated extends BankaccountBase.extend<populated>("populated")({
  organisation: Organisation
}) {}

const decoded = S.decodeUnknownSync(populated)({
  id: "efgh",
  bank_account_number: "5678",
  organisation: {
    id: "org2",
    name: "Org 2"
  }
})
console.log("decoded", decoded, decoded.label)
```
The confusing part to me is the way the classes are created when changing them in the original: How come the decoded object is a plain object if the class schema is used, and how come `decoded.label` is turned into a plain value from a getter when trying to extend the class. Normal schema Structs actually do allow this modification of the originals, but then I lose the convenience of having the opaque type  and custom getters and setters.

**Comment by gcanti** [comment]
@Nvveen The reason is that `Schema.Class` defines a transformation (see: https://effect.website/docs/schema/classes/#class-schemas-are-transformations).  
As soon as you apply an operator like `Schema.omit`, the schema is converted back into a `Schema.Struct`.
