### ISSUE TITLE
Failures triggered in Effect.all with concurrency > 1 are not properly forwarded to devtools 

### ISSUE THREAD

**Issue by anglinb** [Effect-TS/effect#4072]
### What version of Effect is running?

3.11.2

### What steps can reproduce the bug?

Use this example: https://effect.website/play#3f1b03628f61

If you comment out the `concurrency: 2` it will work.

![CleanShot 2024-12-03 at 19 08 05@2x](https://github.com/user-attachments/assets/0fafb438-3535-42a7-adb8-180e5c0783f4)
![CleanShot 2024-12-03 at 19 07 50@2x](https://github.com/user-attachments/assets/0f67f4db-8d4e-4ac1-9139-1bd9fabcc0f2)

```typescript
import { NodeRuntime } from "@effect/platform-node"
import { Effect } from "effect"
import { DevToolsLive } from "./DevTools"

const program = Effect.gen(function*() {
  yield* Effect.log("Welcome to the Effect Playground!")
  yield* Effect.all([
    Effect.succeed("success").pipe(Effect.withSpan("success")),
    Effect.fail("failure").pipe(Effect.withSpan("failure"))
  ], {
    concurrency: 2
  })
}).pipe(Effect.withSpan("program", {
  attributes: { source: "Playground" }
}))

program.pipe(
  Effect.provide(DevToolsLive),
  NodeRuntime.runMain
)

```

### What is the expected behavior?

I would expect the spans to capture the exception the way they do when no concurrency is enabled.

**Comment by tim-smart** [comment]
Fixed in the latest playground :) https://effect.website/play#d6d49cea57bb
