### ISSUE TITLE
Effect-Schema tuples serialized to JSON Schema do not conform to the spec

### ISSUE THREAD

**Issue by dmaretskyi** [Effect-TS/effect#4116]
### What version of Effect is running?

effect@3.10.15, @effect/schema@0.75.5

### What steps can reproduce the bug?

```ts
const jsonSchema = JSONSchema.make(S.Tuple(S.String, S.Number));
console.log({ jsonSchema });
```

### What is the expected behavior?

The schema should serialize according to the spec:
```json
{
  "type": "array",
  "prefixItems": [
    { "type": "string" },
    { "type": "number" },
  ]
}
```

### What do you see instead?

The schema uses "items" key which is incorrect according to the latest spec:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": [
    {
      "type": "string"
    },
    {
      "type": "number"
    }
  ],
  "minItems": 2,
  "additionalItems": false
}
```

### Additional information

See the notes on tuple validation in https://json-schema.org/understanding-json-schema/reference/array#tupleValidation

**Comment by gcanti** [comment]
AFAIK "prefixItems" is not part of Draft 7 (and introduced in JSON Schema 2020-12 specification). From the link you provided:

> Draft-specific info
> In Draft 4 - 2019-09, tuple validation was handled by an alternate form of the items keyword. When items was an array of schemas instead of a single schema, it behaved the way prefixItems behaves.
